### ISSUE TITLE
Abstract class extension of DomainManager with only virtual Query()

### ISSUE THREAD

**Issue by AndrewGaspar** [Azure/azure-mobile-apps-net-server#10]
My scenario is that I want to implement a DomainManager<T> with a custom view of the underlying DbSet<T> such that it can only see items in the data set that contain a token matching the current user ID. Right now I have to implement my own DomainManager<T> that re-implements everything in EntityDomainManager<T> even though all I want to do is disallow access to items that the user is not authorized to access.

I could obviously implement this check at a higher level of abstraction (controller level), but since I have several objects in my database that "belong" to a particularly user, moving the logic into a custom DomainManager would keep the Controller code simple, barely changing from the default Mobile Services Controller templates.

Essentially what I want is:

``` csharp
abstract class FilteredDomainManager<TData> : DomainManager<TData>
{
    protected abstract IQueryable<TData> Query(); // essentially base.Query().Where(additionalCheck);
}
```

or even:

``` csharp
abstract class FilteredDomainManager<TData> : DomainManager<TData>
{
    protected abstract Expression<Func<TData, bool>> Filter(); // this filter is applied to all queries
}
```

Then I should be able to extend FilteredDomainManager<TData> and override that one method, and otherwise get the behavior of EntityDomainManager.

This shouldn't be too difficult to implement - it looks like currently one could extend EntityDomainManager and overload Lookup and Query and get the same behavior, but I get the sense this would be invoking undocumented behavior. I'd even be happy with a virtual method I could override on EntityDomainManager that would guarantee my filter would get inserted into every query against the DbSet.

**Comment by adrianhall** [comment]
I'm closing this as you can do this already at the controller level, which is logically where it would fit.  A DbSet == tablecontroller.  I abstract the filter into it's own LINQ extension method - see http://aka.ms/zumobook chapter 3 for examples.
