### ISSUE TITLE
Support for ASP.NET 5.0

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/azure-mobile-apps-net-server#100]
Hi,

Does this SDK run seamlessly on ASP.NET 5.0. We need to test if this works inside a Linux docker. Is any one aware what might be the problem area if the server side SDK needs to be ported to ASP.NET 5.0.

Thanks and regards
Venkatesh

**Comment by adrianhall** [comment]
No - this SDK is for ASP.NET 4.6.  We have support of ASP.NET Core on the backlog.

**Comment by VenkateshSrini** [comment]
Hi Adrian Hall,

By what time are you planning to provide the same. We have a couple of
customers on AWS. They over all liked the concept of Mobile app as backend.
Also they wanted to be vendor independent deployment hence we have to host
these servers in docker container as a first step. Once they are able to
feel the benefits then we can have them hosted in Azure step by step. So
there are some usecases like this coming. If you feel that it involves
quite some effort, please at least let us know what challenges we will face
if we do this customization? Will there be some road block owing to
non-availability of components? Will there be performance challenges.

**Comment by adrianhall** [comment]
Unfortunately, I don't have a timeline to share at this time.  Our belief is that the OData implementation (and EF7 changes) will cover the bulk of the time.  However, we have not started digging into it - it's quite possible that other things bite us.

**Comment by VenkateshSrini** [comment]
Hi Adrian Hall,
Is there some person in Microsoft that you are aware of who has started getting their hands dirty on this

-----Original Message-----
