### ISSUE TITLE
Unable to use the Try out button in IE11

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/azure-mobile-apps-net-server#102]
Hi,
I have hosted my app in Azure as a mobile app (App Service). Unfortunately the try out button in Swagger definition is not working in IE11. It simply hangs. But the same works in Edge and Google chrome. Could any one tell me what could be the potential issue.

Thanks and regards
Venkatesh

**Comment by brettsam** [comment]
Thanks for filing this issue. I'm seeing the same thing. The error I'm seeing in IE11 is coming from swagger-ui: `Object.keys: argument is not an Object`. I'll have to do some investigation to see if this is something that the Mobile Apps config is doing or if it's a bug in Swagger somewhere.

**Comment by VenkateshSrini** [comment]
Hi Brett,

Any updates on this issue. Could you please point out to a possible resolution 

-----Original Message-----

**Comment by VenkateshSrini** [comment]
Hi Brett,

Any updates on this, could you please tell me where to look into so that I can also help in the same.

Thanks and regards
Venkatesh

**Comment by lhughey** [comment]
@VenkateshSrini I've given up on the App Service and have started developing with Mobile Apps in Azure.  One of the downfalls of doing so is that the "try it out button" has been abandoned.  On top of that, the official documentation for how to integrate swagger is out of date and doesn't work.  I found a blog which show you how to add swagger to to your services, quickly.  The instructions are found at 
https://github.com/Azure/azure-mobile-apps-net-server/wiki/Adding-Swagger-Metadata-and-Help-UI-to-a-Mobile-App

I've tested it, and it works wonderfully.  I hope this helps you, and others.

**Comment by VenkateshSrini** [comment]
I'm using the same link that you have provided. But try out button is still the challenge 

-----Original Message-----

**Comment by lhughey** [comment]
I've been using Edge and Chrome to run things (and not IE) without issue.  I'm sorry, I'm not going to be able to help.

**Comment by adrianhall** [comment]
I'm going to close this.  The UI is provided by the Swagger group - we just include it.  As a result, we are unable to affect changes in the Swagger portal.
