### ISSUE TITLE
Unable to add unit test to Azure Mobile App

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/azure-mobile-apps-net-server#104]
Hi,
When we try to add an Azure web api, there is an option to add the unit test, but the same is disabled for Azure mobile app. Could you please provide me the steps to add Unit test to mobile app.

Thanks and regards
Venkatesh
![mobile app server unit test](https://cloud.githubusercontent.com/assets/1167152/13898982/dff85878-ee08-11e5-90b9-045edcd78ad5.png)

**Comment by deman4ik** [comment]
@VenkateshSrini You can just add new "Unit Test Project" to your Azure Mobile App Solution after creating.

**Comment by adrianhall** [comment]
Per @deman4ik - just add a unit test.  We don't supply default unit tests, so the app doesn't need to do anything.
