### ISSUE TITLE
'Name' Claim key is different for Google identity provider

### ISSUE THREAD

**Issue by danielloczi** [Azure/azure-mobile-apps-net-server#109]
Our application extracts the authenticated user's full name from claims.
The claim key that we are using is 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'. (this is located at the ClaimTypes.Name string constant).
This works well for Microsoft,Facebook, and Twitter identity providers, but for Google the claims don't have the expected key, but it contains a "short" version of the key: 'name'.

Here is the expected key to get the full name:
![fb-claimname-ok](https://cloud.githubusercontent.com/assets/11349934/14316218/1f894d74-fc02-11e5-8ea4-45bf6a9af854.jpg)

In case of Google, it looks like this:
![google-claimname-issue](https://cloud.githubusercontent.com/assets/11349934/14316100/7334e5c4-fc01-11e5-84a4-a9d5c1975b90.jpg)

So finally I had to write a workaround to handle this situation:

``` c#
 if (claims.ContainsKey(ClaimTypes.Name))
            {
                return claims[ClaimTypes.Name];
            }
            else
            {                
                if (claims.ContainsKey("name"))
                {
                    return claims["name"];
                }
            }
```

I think this is bug. Could you please check it and fix it?
The Microsoft.Azure.Mobile.Server package version is v1.1.157.1

Thanks!

**Comment by brettsam** [comment]
You're correct, it looks like we're not mapping the Google claims the same as the other providers. This is part of App Service Authentication but I'll leave this issue open until a fix is deployed.

**Comment by danielloczi** [comment]
Thank you for the feedback!

**Comment by mattchenderson** [comment]
@cgillum Any updates here?

**Comment by adrianhall** [comment]
Since this is a part of App Service Authentication and not a part of this SDK, closing.
