### ISSUE TITLE
localdb clustered index from EntityData migration

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-apps-net-server#11]
Locally for debugging and unit testing, I am trying to use localdb. With the current implementation of EntityData the clustered indexes cause issues with error:

System.Data.SqlClient.SqlException : Cannot create more than one clustered index on table 'dbo.TableName'. Drop the existing clustered index on 'PK_dbo.TableName' before creating another.

Doesn't occur when running in SQL Azure, but would love to be able to enable this scenario, especially for local testing.

**Comment by brettsam** [comment]
You could you be running into the same SqlGenerator issue that I looked into for this SO question: http://stackoverflow.com/questions/32141513/how-to-initializing-the-code-first-entity-framework-database-in-an-azure-mobile/32214696#32214696.

However, I think that this would affect you both SQL Azure and localdb, so maybe you're running into something different. 

Can you see if that SO answer takes care of it, and if not, do you have a quick scenario that I could run through to reproduce it?

**Comment by damienpontifex** [comment]
That solved it thanks.
