### ISSUE TITLE
The request could not be completed. (Unauthorized) at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient

### ISSUE THREAD

**Issue by parth23** [Azure/azure-mobile-apps-net-server#110]
I am trying to get facebook user profile details after login in xamarin app uisng azure mobile app.
But I get exception on Xamarin mobile app (i.e. The request could not be completed. (Unauthorized) at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient.......)
I try to attach debugger and check on azure mobile service then I get this.User.Identity.IsAuthenticated is false

![asd](https://cloud.githubusercontent.com/assets/17453977/14317875/efa88b08-fc27-11e5-91bb-a55d8371cd10.png)

![asd1](https://cloud.githubusercontent.com/assets/17453977/14317887/fb3c2e3e-fc27-11e5-97d7-0c9e2a6161cf.png)

Here is my xamarin request method(Client Side Code): 

        async void OnLoginClicked(object sender, EventArgs e)
        {
            MobileServiceUser user;

            try
            {
                var client = DependencyService.Get<IMobileClient>();
                // The authentication provider could also be Facebook, Twitter, or Microsoft

                user = await DependencyService.Get<IMobileClient>().LoginAsync(MobileServiceAuthenticationProvider.Facebook);
                GetUserinfo();

                Navigation.InsertPageBefore(new TodoList(), this);
                await Navigation.PopAsync();
            }
            catch (InvalidOperationException ex)
            {
                if (ex.Message.Contains("Authentication was cancelled"))
                {
                }
            }
            catch (Exception ex1)
            {
            }
        }

        public async void GetUserinfo()
        {
            MobileServiceClient client = new MobileServiceClient(Constants.ApplicationURL);
            Dictionary<string, string> header = new Dictionary<string, string>();

            try
            {
                var userInfo = await client.InvokeApiAsync("Values", HttpMethod.Get, null);
            }
            catch (Exception ex)
            {
            }
        }

ServerSide Code:

    [MobileAppController]
    public class ValuesController : ApiController
    {
       
        public async Task<string> Get()
        {
            try {
                ClaimsPrincipal principal = this.User as ClaimsPrincipal;
                //return this.User.Identity.IsAuthenticated.ToString();
                string provider = principal.FindFirst("http://schemas.microsoft.com/identity/claims/identityprovider").Value;

                Microsoft.Azure.Mobile.Server.Authentication.ProviderCredentials creds = null;
                if (string.Equals(provider, "facebook", StringComparison.OrdinalIgnoreCase))
                {
                    creds = await this.User.GetAppServiceIdentityAsync<Microsoft.Azure.Mobile.Server.Authentication.FacebookCredentials>(this.Request);
                }
                //else if (string.Equals(provider, "google", StringComparison.OrdinalIgnoreCase))
                //{
                //    creds = await this.User.GetAppServiceIdentityAsync<GoogleCredentials>(this.Request);
                //}
                //else if (string.Equals(provider, "twitter", StringComparison.OrdinalIgnoreCase))
                //{
                //    creds = await this.User.GetAppServiceIdentityAsync<TwitterCredentials>(this.Request);
                //}

                string userName = string.Format("{0}:{1}", creds.Provider, creds.Claims[ClaimTypes.NameIdentifier]);
                return userName;
            }
            catch(Exception e)
            {
                return e.StackTrace;
            }
        }
    }

**Comment by brettsam** [comment]
It looks you're creating a new MobileServiceClient before calling InvokeApiAsync("Values"). This client won't know what the current user's authentication token is, since it is stored in the client instance that performed the login.

If you can pull the same client from your DependencyService and use that, I think it'll work as expected.

**Comment by parth23** [comment]
@brettsam 
Without creating client how can I call API controller?

**Comment by parth23** [comment]
@brettsam 
You are right now its working Thanks @brettsam

**Comment by brettsam** [comment]
Great!

**Comment by parth23** [comment]
@brettsam 
Thank you very much for your support and now I have been able to retrieve basic facebook and google profile data. However I have noticed that google profile data doesn't return gender and dateofbirth information. I have checked in azure portal but it doesn't allow configuring  SCOPE for google authentication the way it provide for the facebook. So in this case are you aware how to retrieve additional SCOPE information for google profile
Thanks.

Here is my code:
 else if (string.Equals(provider, "google", StringComparison.OrdinalIgnoreCase))
            {
                creds = await this.User.GetAppServiceIdentityAsync<GoogleCredentials>(this.Request);
                user.firstName = creds.Claims.Keys.Contains(ClaimTypes.GivenName) ? creds.Claims[ClaimTypes.GivenName] : "Not Available/Private";
                user.lastName = creds.Claims.Keys.Contains(ClaimTypes.Surname) ? creds.Claims[ClaimTypes.Surname] : "Not Available/Private";
                user.gender = creds.Claims.Keys.Contains(ClaimTypes.Gender) ? creds.Claims[ClaimTypes.Gender] : "Not Available/Private";
                user.dateOfBirth = creds.Claims.Keys.Contains(ClaimTypes.DateOfBirth) ? creds.Claims[ClaimTypes.DateOfBirth] : "Not Available/Private";
                user.email = creds.Claims.Keys.Contains(ClaimTypes.Email) ? creds.Claims[ClaimTypes.Email] : "Not Available/Private";
            }
