### ISSUE TITLE
JWT validation failed: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.InMemorySymmetricSecurityKey

### ISSUE THREAD

**Issue by danielloczi** [Azure/azure-mobile-apps-net-server#111]
In the log file of a Mobile App Service I found warnings and errors. I tried to figure out the root reason of these log entries, but didn't find it. 

An extract from the log (sensitive data was removed):

`PID[32116] Error       Failed to read the 'Nonce' cookie for site '**********.azurewebsites.net': Nonce expired on 2016-04-**T**:**:**.0000000`

```
PID[25160] Warning     JWT validation failed: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.InMemorySymmetricSecurityKey
'.
Exceptions caught:
 ''.
token: '{"typ":"JWT","alg":"HS256"}.{"fullrow":"all","Dbg2":"login","ver":"3","uid":"sid:D226******************","iss":"urn:microsoft:windows-azure:zumo","aud":"urn:microsoft:windows-azure:zumo","exp":1449********,"nbf":1447********}
RawData: *************************MyIsInVpZCI6InNpZDpEMjI2QTNCNUYyODI0QzQwQjk3OTNERjBBQjkzNDI0MiIsI**************************Nyb3NvZnQ6d2luZG93cy1henVyZTp6dW1vIiwiYXVkIjoidXJuOm1pY3Jvc29mdDp3*************************JlOnp1bW8iLCJleHAiOjE0NDk1OTY3MzMsIm5iZiI6MTQ0NzAwNDczM30.oxJ7*********************************'.
```

Mobile App Server version v1.1.157.1. The service is configured to use Facebook, Google, Twitter and Microsoft identity providers. 
I double checked the SIDs that are located in these entries (searched in our user db), and it seems that they are all related to Facebook accounts.

Could you please help me to solve this issue?
Thank you in advance!

**Comment by cgillum** [comment]
The token you're sending to the Mobile App API does not look like a Mobile App authentication token. Rather, it looks like a legacy Mobile Services authentication token.  That would explain why validation is failing.  Are you using the latest Mobile App Client SDK?

**Comment by mattchenderson** [comment]
Looks like this has been answered. If you have any additional questions, let us know.
