### ISSUE TITLE
Unable to use Microsoft.Azure.Mobile.Server.Swagger with custom authentication

### ISSUE THREAD

**Issue by AndrewNikolin** [Azure/azure-mobile-apps-net-server#113]
Hi! I've installed Swagger according to this wiki page https://github.com/Azure/azure-mobile-apps-net-server/wiki/Adding-Swagger-Metadata-and-Help-UI-to-a-Mobile-App, but the problem is that I'm using custom authentication in my app, so I need to provide a header "x-zumo-auth" with a value of API key. Is it possible to make Swagger send this header with a key I provide somewhere in UI?

**Comment by brettsam** [comment]
You'll need to do some customization but yeah that should be possible. Just so I'm clear -- you don't want the login behavior that currently logs you in via Facebook/Microsoft/etc, and instead you'd like to enter a string somewhere that gets put into x-zumo-auth? And that API key is a static string that doesn't require any logging in?

**Comment by AndrewNikolin** [comment]
No, it's not static, I've made my custom implementation of login using Microsoft.Azure.Mobile.Server.Login, this article http://www.newventuresoftware.com/blog/custom-authentication-with-azure-mobile-apps and this part of App Service documentation https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/#how-to-work-with-authentication
String is not static and user acquires it via API. There is custom Auth API controller, client POSTs login data to it and API generates JwtSecurityToken

**Comment by DawidSadlik** [comment]
Could anybody provide definition of LoginResult and LoginResultUser class. I cannot figure out how them should look like. I've tried many times and always I get NullReference Exception after call LoginAsync of MobileAzureClient.

**Comment by adrianhall** [comment]
The LoginResult and LoginResultUser are documented in my book - http://aka.ms/zumobook - direct link: https://github.com/adrianhall/develop-mobile-apps-with-csharp-and-azure/blob/master/Chapter2/Backend/Models/LoginResult.cs
