### ISSUE TITLE
Authenticate and access data within Mobile App from a Web App in the same Azure App Service deployment

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-net-server#115]
I've been searching for the ability to create a Web App and a Mobile App within the same Azure App Service deployment and be able to authenticate once to access them both. This also would include the ability to have the Mobile App DBs to be the main DBs in the App Service and to have the DBs accessible from both the Web App and the Mobile App.

So far, I have been unsuccessful in my search which is why I'm posting this as an issue here. Is it possible to achieve the above statements? I'd like to know that my mobile app and the data that users create in it can be surfaced in a Web App with the same authentication in the future. If this is possible, is there documentation on how to do it?

Thanks,

John

**Comment by renzska** [comment]
When I stated "to be able to authenticate once to access them both", what I meant was to be able to use the same authentication source for both the web application and mobile application.

UPDATE:

I have been able to get this working by adding a mvc view to my mobile app server which then added the required dlls. I basically now have a hybrid mobile/web app service that hosts both. I am then using the Aurelia framework, loaded in my Index.cshtml as my web app front end. From there, I can authenticate by hitting /.auth/login/{provider} and /.auth/logout to logout. I am also able to hit the Mobile AppController apis from the web app after logging in.

I'm now looking for some documentation on how best to use the App Service Authentication from the Web App to save the user information/token securely between browser sessions. I have seen some mention of this here: https://azure.microsoft.com/en-us/blog/announcing-app-service-authentication-authorization/. Is there any documentation on how to do this?

Is what I'm doing above a supported model? I am not separating out the web app and mobile app services due to authentication sources available from facebook and google, wanting to have the same provider userId for both applications.

Thanks.

**Comment by cgillum** [comment]
What you're doing should be perfectly fine, though there may be a few wrinkles since it's a less common scenario (mixing web and mobile authentication together).  Of course, if you run into any issues, we'll make sure to address them.

Can you elaborate on what you mean by saving user information/tokens securely between browser sessions?

**Comment by renzska** [comment]
Basically from what I can see, when authenticating in the browser to ./auth/login/{provider}, the cookie, AppServiceAuthSession, stores the token needed for authentication. I have to add this cookie to the HttpClient from my MVC 5 app when I call the MobileApiController for it to not return a 401 Unauthorized.

The AppServiceAuthSession cookie has the Expires/MaxAge value set of "Session". After a period of time, using Google Chrome, I have to reauthenticate. I have yet to determine if this is because the cookie no longer exists or if the AppServiceAuthSession token has expired.

Because there is not much documentation on the new App Service Authentication, I'm unsure of the best way to maintain a users login. The login providers I am using are Google and Facebook. 

What I'm thinking of doing now:

I could create a non-expiring cookie or use local storage to track which provider they selected on previous login and auto send them through /.auth/login/{provider} with a return url of the page they were on, upon receiving a 401. That should authorize them without requiring them to login to the provider unless they logged out of the provider explicitly.

On a side question, can you detail what the different cookies created after login are for?

Cookies after .auth/login/{provider}:

AppServiceAuthSession
ARRAffinity
__RequestVerification

Thanks,

John

**Comment by cgillum** [comment]
To answer your cookie questions, AppServiceAuthSession is the cookie used for authenticating, as you discovered.  It currently expires after 8 hours.

ARRAffinity is a cookie used for maintaining sessions with specific App Service backend workers.  See this for more details: https://technet.microsoft.com/en-us/library/dd443543(v=ws.10).aspx

I'm not familiar with __RequestVerification.  That might be coming from your own application and/or framework.

**Comment by renzska** [comment]
I just found your blog and saw the /.auth/refresh path. This would works for me using Google, but not for Facebook, however, their token is 60 days, so not much of an issue. However, with you stating that the AppServiceAuthSession expires after 8 hours, how is prolonged authentication able to be achieved for Google and Facebook logins from a Web App?

In my mobile app, I create a DelegatingHandler and override SendAsync to check for an "Unauthorized" response, but that only applies to Google Auth in my case and relies on the fact that you currently have 72 hours (from my post on your blog and your response).

```
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
		{
			if (this.Client == null)
			{
				throw new InvalidOperationException("Make sure to set the 'Client' property in this handler before using it.");
			}

			// Cloning the request, in case we need to send it again
			var clonedRequest = await CloneRequest(request);
			var response = await base.SendAsync(clonedRequest, cancellationToken);

			if (response.StatusCode == HttpStatusCode.Unauthorized)
			{
				Debug.WriteLine("SendAsync: HttpStatusCode.Unauthorized");
				// Oh noes, user is not logged in - we got a 401
				// Log them in, this time hardcoded with Facebook but you would
				// trigger the login presentation in your application
				try
				{
					DialogService.HideLoading();
					if (string.IsNullOrEmpty(Settings.LoginProvider))
					{
						App.Logout();
					}
					else
					{
						//http://cgillum.tech/2016/02/01/architecture-of-azure-app-service-authentication-authorization/
						//http://cgillum.tech/2016/03/07/app-service-token-store/
						//https://azure.microsoft.com/en-us/documentation/articles/web-sites-enable-diagnostic-log/

						// Calling /.auth/refresh will update the tokens in the token store
						// and will also return a new mobile authentication token.
						Debug.WriteLine("Attempting to refresh token");
						JObject refreshJson = (JObject)await Client.InvokeApiAsync("/.auth/refresh", HttpMethod.Get, null);

						string newToken = refreshJson["authenticationToken"].Value<string>();
						Client.CurrentUser.MobileServiceAuthenticationToken	= newToken;
						Debug.WriteLine("After refreshing token: " + newToken);
						
						// we're now logged in again.

						// Clone the request
						clonedRequest = await CloneRequest(request);

						// Save the user to the app settings
						this.saveUserDelegate(Client.CurrentUser); //save updated token

						clonedRequest.Headers.Remove("X-ZUMO-AUTH");
						// Set the authentication header to the new header
						clonedRequest.Headers.Add("X-ZUMO-AUTH", Client.CurrentUser.MobileServiceAuthenticationToken);

						// Resend the request
						response = await base.SendAsync(clonedRequest, cancellationToken);

						if (response.StatusCode == HttpStatusCode.Unauthorized)
						{
							Debug.WriteLine("Unable to refresh token");
							App.Logout();
						}
					}
				}
				catch (InvalidOperationException)
				{
					// user cancelled auth, so lets return the original response
					return response;
				}
			}

			return response;
		}
```

**Comment by cgillum** [comment]
We don't expose any way of configuring extended access when using cookies. In most cases, it shouldn't matter since SSO will ensure the user doesn't need to re-enter their credentials.  If you're writing a SPA app that uses AJAX to call the backend APIs then I could see how this could interrupt the flow in a non-idea way.  Is that what your concern is?  If so, you may want to consider using the JavaScript client SDK and rely on the zumo token flow (with token refresh) to avoid any interruption.

You delegating handler looks good to me, though you will want to check for the case where calling /.auth/refresh fails so that you don't hit a null-ref exception trying to access properties of your refreshToken.

**Comment by renzska** [comment]
That is my concern. Using https://github.com/Azure/azure-mobile-apps-js-client/, would that allow me to use an HttpClient in .NET backend code to grab the data from my controllers that way? I assume I would have to grab the headers of the Request and add them to the .NET backend HttpClient (I have to do that with the cookies now). In reality, I may switch to just calling my apis using JS directly, but I wanted to see if the above idea was a viable solution.

Thanks for the info on the null ref exception in my code.

**Comment by cgillum** [comment]
I might be missing some context. What is your backend doing that requires you to grab headers/cookies?

**Comment by renzska** [comment]
I was trying to use a basic MVC Controller that calls into the MobileAppController using an HttpClient. That required the copying of the cookies and headers. I've decided that may not be the best approach and am moving to using Aurelia with TypeScript and webpack. I'll look into using the mobile apps js client library for auth from my Aurelia app (all hosted within the the MobileApp).

**Comment by triple888three** [comment]
Any updates or recommendations on this discussion?  Did you have any luck with the mobie apps js client?

I'm trying to build a Web App as another cross-platform client to my existing Azure App + Xamarin (iOS/Android/UWP) setup.  Is there a way to re-use a Mobile Service Client for App Service Auth & API calls.

**Comment by adrianhall** [comment]
Cleaning up - looks like original issue was solved / answered.
