### ISSUE TITLE
x-zumo-auth not set when calling /.auth/login/provider directly

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-net-server#116]
When calling /.auth/login/provider from my hybrid mobile app/web app, the x-zumo-auth is not set. From what I can tell, the header is specific to mobile app logins through the mobile app client sdk. While not a huge issue, due to the lack of that header, the GetAppServiceIdentityAsync method does not work. Because of this, I have to get my user data differently on the web app.

I currently rely on the lack of identityprovider being set in the web app to determine where I'm from (I guess I could change this to check to see if I'm missing the x-zumo-auth header).

```
var claim = claimPrincipal.FindFirst("http://schemas.microsoft.com/identity/claims/identityprovider");
if (claim != null)
                    {
                        switch (claim.Value)
                        {
                            case "facebook":
                                return IdentityProvider.Facebook;

                            case "google":
                                return IdentityProvider.Google;

                            case "microsoft":
                                return IdentityProvider.Microsoft;

                            case "twitter":
                                return IdentityProvider.Twitter;

                            default:
                                return IdentityProvider.None;
                        }
                    }
                    else
                    {
                        return IdentityProvider.FromWebApp;
                    }
```

I then know that I need to get my data differently (ClaimsProvider vs ProviderCredentials).

It would be nice to be able to get the data in the same way from the web app and from the mobile app.

Thanks,

John

**Comment by cgillum** [comment]
In general, the Mobile App SDKs are not going to work very well when logging in using something other than the Mobile App Client SDK.  Instead, you'll likely need to use HTTP primitives to access the information you want.

Internally, GetAppServiceIdentityAsync makes a call to /.auth/me using the x-zumo-auth token as you mentioned. If x-zumo-auth is not available, you can instead use an HTTP client to call /.auth/me and include the session cookies that were sent by the browser to your API. Another option you have is to make this call from JavaScript in the browser. That should include the session cookies automatically and make it easier to consume the data.
