### ISSUE TITLE
MicrosoftAccount userID is wrong value

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-mobile-apps-net-server#117]
MicrosoftAccountCredentials.UserId gives you the field corresponding to "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" (Display name) when it should be "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier" (Provider ID)

Workaround is to just use creds.Claims[ClaimTypes.NameIdentifier]

**Comment by mattchenderson** [comment]
This will be a breaking change.

**Comment by adrianhall** [comment]
@mattchenderson Can you give some more details on this?  How do I actually create a MicrosoftAccountCredentials object where this is a problem?  Do you have a code snippet?
