### ISSUE TITLE
is it possible to load default page to sitename/app in mobile apps ?

### ISSUE THREAD

**Issue by nagen1** [Azure/azure-mobile-apps-net-server#118]
Question!
is it possible to get ride of **"This mobile app is up and running"** page and when user enters the sitename redirect/route him to sitename/app folder where I can pretty much create a AngularJS website in my project folder. FYI - I'm a Dev beginner

in current site: when I open the site (www.navaras.com) it's taking me to blue screen and when I go to (www.navaras.com/app) it displays my app that I am trying attach it to mobile app to serve desktop web users.

why I want to do it ?
On a typical note I want my app to serve all devices, web, mobile, tablet and I feel that mobile app solution is the only lean solution to do rapid application development. Per say, mobile service is just a backend stack and it doesn't allow it... I wonder why not ? by doing it, developers don't need to create 2 services in azure (1. mobile app, 2. web app)

Appreciate it.

**Comment by adrianhall** [comment]
Yes, it is.   In your App_Start code is the following:

```
            HttpConfiguration config = new HttpConfiguration();

            new MobileAppConfiguration()
                .UseDefaultConfiguration()
                .ApplyTo(config);
```

The `.UseDefaultConfiguration()` is a convenience method that expands out to the following:

```
            HttpConfiguration config = new HttpConfiguration();

            new MobileAppConfiguration()
                .AddTables(
                    new MobileAppTableConfiguration()
                        .MapTableControllers()
                        .AddEntityFramework())
                .MapApiControllers()
                .AddMobileAppHomeController()
                .AddPushNotifications()
                .ApplyTo(config);
```

You can find the reference source here:  https://github.com/Azure/azure-mobile-apps-net-server/blob/76cd709479e8e96a26a711a6fc31cca35b68ef70/src/Microsoft.Azure.Mobile.Server.Quickstart/Extensions/QuickstartMobileAppConfigurationExtensions.cs

Simply replace the UseDefaultConfiguration() with the expanded version and then remove the `.AddMobileAppHomeController()` which implements a standard MVC controller for the home page.
