### ISSUE TITLE
Server should indicate when request URL is too long

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps-net-server#119]
Ported from  https://github.com/Azure/azure-mobile-services/issues/892

> Hi, I spent a day trying to debug a 404 error when my mobile app called my server with a filter that was large. In the old version (Azure Mobile Services) the failure error reported to the client was something like "Request Uri Too Long". The current server just reports a 404 and the request fails to hit the table controller so there is no debugging that you can do.
> 
> I probably should have thought of it sooner, but if I had seen the uri too long error I would have increased the querystring and url size in the web.config and been done with it. It would be nice if this was documented somewhere or if the error could be more descriptive than just a 404.

**Comment by adrianhall** [comment]
This is an IIS thing - the actual error is 404.14 as according to this table:

HTTP Substatus Description
404.5 URL Sequence Denied
404.6 Verb Denied
404.7 File Extension Denied
404.8 Hidden Namespace
404.10 Request Header Too Long
404.11 URL Double Escaped
404.12 URL Has High Bit Chars
404.13 Content Length Too Large
404.14 URL Too Long
404.15 Query String Too Long
404.18 Query String Sequence Denied
404.19 Denied by Filtering Rule

In the client, we could trap this, but it will still show as a 404.

**Comment by adrianhall** [comment]
This is consistent with the following IIS error code table:

HTTP Substatus Description
404.5 URL Sequence Denied
404.6 Verb Denied
404.7 File Extension Denied
404.8 Hidden Namespace
404.10 Request Header Too Long
404.11 URL Double Escaped
404.12 URL Has High Bit Chars
404.13 Content Length Too Large
404.14 URL Too Long
404.15 Query String Too Long
404.18 Query String Sequence Denied
404.19 Denied by Filtering Rule
