### ISSUE TITLE
Why does my controller not map all changed properties in my patch json?

### ISSUE THREAD

**Issue by jmichas** [Azure/azure-mobile-apps-net-server#120]
I have been trying to debug this for a day. When my client updates a local item I can set a break point and inspect the client db and see the change is written and a record is added to the operation table for sync. When I call sync I can intercept the call and see that the JObject being passed to the server is correct and has the changes that were written to the local db. When I break on the server controller for the patch I do not see that all the properties are correct. Some, of the properties are populated some are dropped. I have found no pattern, some GUIDs are zeroed while others are populated most if not all ints are zeroes instead of the value in the JSON being sent to the server.

I am not sure what else to check. I will also say though, that this was an upgraded Mobile Services server app that worked perfectly, since Ive been trying to upgrade the client and server I have encountered many problems not outlined in the upgrade documentation.

One other question, I noticed that the version and id properties in the JSON sent to the server are lower case, but the other properties are Pascal. The server response is camelCased. I did try manually sending the JSON after camelCasing all the properties and none of them are populated when I break on the server controller patch.

**Comment by lindydonna** [comment]
@jmichas Could you provide your server SDK controller & data class?  I haven't seen this issue before. It is most likely a mapping issue, but I can help narrow it down.

**Comment by jmichas** [comment]
@lindydonna Please see the code in this gist https://gist.github.com/jmichas/f9663ab3048c50e668619686f863c8d7

What mapping would be the issue? The Automapper code? My Dto and Domain are identical unless something changed from Mobile Services to Mobile Apps. Is there a way to debug further upstream where the JSON that is posted in the patch is converted to an object?

**Comment by lindydonna** [comment]
Ah, Automapper is likely the culprit here. It's possible that it is interfering with the JSON serialization. Try removing automapper entirely, and see what happens. Btw, you could just remove some columns from your DTO by adding JsonIgnore, so you may not need automapper at all. 

To debug further upstream, you'll need to set a breakpoint somewhere in the Web API stack, but I'm not sure exactly where that is. Try searching/posting on StackOverflow with the Web API tag. 

In terms of changes in Mobile Services vs. Mobile Apps, we did change it so that all system properties are queried by default. Previously, you needed to use __systemProperties=*, but now you will get UpdatedAt, CreatedAt, and Version returned in the response. See the System Properties section here: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-net-upgrading-from-mobile-services/#updating-the-server-project.

**Comment by jmichas** [comment]
Isn't Automapper what the MappedEntityDomainManager uses? 
I thought I was required to create maps for the domain manager to use.

The JSON sent to the controller is correct from the client, I have checked and double checked that the client is doing the right thing. But I do a push then a pull, so while the push is sending the correct JSON, it is never written to the server database, and so then the pull brings down the old version and overwrites the client's changes.

**Comment by lindydonna** [comment]
I meant, use EntityDomainManager to help narrow down the problem. It's possible that your automapper config is not deserializing the json correctly, for instance.

**Comment by jmichas** [comment]
So at the point when I can break on in the controller and inspect the patch what has happened at that point? I thought that was just a representation of the deserialized JSON that hit the controller. Is that the mapped data?

Im going to try and write some tests to see if I can get it to break the same way again.

**Comment by lindydonna** [comment]
If you break on your controller, a lot has already happened. It's gone through both automapper as well as the JSON serializer that is registered by the server SDK. What you need to do is to set a breakpoint and see the actual JSON content of the request and see how it is getting mapped along the way. 

The patch is doing all of this mapping, since you're not accepting a JObject, but rather a Delta<YourDto>.

**Comment by jmichas** [comment]
Dang, I was hoping you would look at my code and see some glaring issue I could fix and be done with it. ;)

**Comment by lindydonna** [comment]
Unfortunately, since you're using automapper, it all gets more complex. I'm 99% sure that's where the problem lies.

**Comment by jmichas** [comment]
So, grrrrr, I think you are right. Ugh, I've got to learn to stop cutting corners. Simply using the Mapper.AssertConfigurationIsValid() has given me a laundry list of members to map. I think in my old code I used an older version of Automapper and it didn't map the virtual nav properties or attempt to Im guessing. I was forced to keep many packages very old in my Mobile Services version of this because I was issuing my own zumo tokens and the JWT library had to be a very specific version or the tokens were invalid. Anyway, once these are fixed Im betting you are correct and the patch data will look correct and all will be good in my world again....until the next bug :)

**Comment by lindydonna** [comment]
Can I go ahead and close this bug?  We can reopen if you have a small repro.

**Comment by jmichas** [comment]
Yeah, I would assume it is good. I will know pretty soon whether it is fixed or not, but I figure if this was a different issue others would have reported it too, it would be major to have properties not update in a sync.

Thank you very much for all your help, I should have posted yesterday :)

**Comment by jmichas** [comment]
Ok, so automapper was not the problem.
I rolled a new controller from scratch and it magically worked when I set a break point in the update patch method. Looking at the patch showed all the properties passed in the JSON via Postman.

So, I started to put things from my original controller back in, mainly the attributes for the class itself. I added [Authorize] and it still worked, then I added [MobileAppController] and that caused the properties to not be deserialized from the JSON.

So, is it true that I do not need the [MobileAppController] attribute on controllers that inherit from TableController<>? Also, if this is the case (or not the case) shouldn't adding that attribute have no effect and not a negative effect? Maybe this is a bug?

**Comment by lindydonna** [comment]
Interesting! @brettsam Shouldn't [MobileAppController] have no effect on a table controller? That might be a bug.

You definitely don't need the attribute, but I am surprised that it actually had an effect.

**Comment by jmichas** [comment]
Yeah, just tested with my original code and it works fine now. Amazing, I spent almost 3 days I think trying to figure this out.

I would say whether its a bug or not you should definitely update the documentation to with a callout that you don't need that attribute on table controllers. I thought you did because in reading the upgrade documentation it states that adding that attribute is one of the things you must do.

**Comment by brettsam** [comment]
There may be a bug here in how we handle [MobileAppController] if it is on a TableController. TableController already has the MobileAppController attribute applied so there is likely some kind of filter or config duplication that's causing issues here. We can handle this better. I've opened an issue to follow up: #123

**Comment by FrancoisM** [comment]
Having a similar issue here.
I'm trying to update an enum column.
When I look at the content of the request in the Initialize method, the updated property has the correct value.
However, when I look in the Patch method, the patch variable doesn't see my updated property as updated (not present in _updatedProperties, which btw shows properties which are not updated) and shows the default value of the enum.
I also had the [MobileAppController] (why I don't know). I removed it but it had no effect.

**Comment by FrancoisM** [comment]
Note that in my local db, the enum seems to be stored as a string and the json content of the request sends the property as a string while in the backend it's an int.

**Comment by FrancoisM** [comment]
Here is my initiliaze method:

```
protected override void Initialize(HttpControllerContext controllerContext)
{
    base.Initialize(controllerContext);
    DomainManager = new EntityDomainManager<TData>(Context, Request);
    var content = Request.Content;
    var jsonContent = content.ReadAsStringAsync().Result;
    try
    {
        var obj = JsonConvert.DeserializeObject<MyClass>(jsonContent);
     }
     catch (Exception)
     {
         //
      }
}
```

obj is correctly desesialized whether I send my enum as a int or a string.
So what happens before the patch method?

Note: I realized that the patch variable _changedProperties array had all the properties send within the content except my enum and the azure fields (id, createat, version etc).

**Comment by FrancoisM** [comment]
I have a custom table controller subsclassing a base one. I had removed [MobileAppController] from the derived class but not the base. Now that I removed it from base it is working!

**Comment by FrancoisM** [comment]
Side note: why is the mobile client is sending all the fields of the entity if only the updated ones are sufficient?

**Comment by adrianhall** [comment]
@FrancoisM  We don't monitor closed bugs.  If you have a new issue, please open a new issue.  Thanks!

**Comment by SplayConsulting** [comment]
This is still an issue. 
I fixed it by removing  [MobileAppController] from the base class.

**Comment by adrianhall** [comment]
Ref #123 - which is the actual class.  You did the right fix.
