### ISSUE TITLE
[MobileAppController] on a TableController should throw

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-mobile-apps-net-server#123]
See #120 for some history. If you put a MobileAppControllerAttribute on a TableController (which already has this attribute internally), you get odd behavior. This is likely due to duplicated filters or duplicated configuration. We should look to detect this and throw, if possible.

**Comment by adrianhall** [comment]
You cannot detect within the [MobileAppController], but you can detect within a TableController, based on https://msdn.microsoft.com/en-us/library/71s1zwct(v=vs.110).aspx#cpconretrievingmultipleinstancesofattributeappliedtosamescope
