### ISSUE TITLE
DateTime Storage and Serialization

### ISSUE THREAD

**Issue by jmichas** [Azure/azure-mobile-apps-net-server#124]
I have an issue with datetimes when they are synced from my client.
I am ensuring that datetimes on my client (as displayed here https://github.com/Azure/azure-mobile-apps-net-client/issues/131) are all stored as UTC and handled as UTC in my objects since I do a lot of calculations on dates in my app.

I have found an issue with my sync process though. When I sync the dates from my client and they are sent up to the server and entered into the SQL database the correct value is entered. When they are read out and sent back down it appears they are treated as Local times and so serialized into a UTC time. I am in the ET USA, so this moves the date time +4 hours. The client then displays an incorrect time to the user. Each round trip to the server for a sync on an updated object shifts the date time +4 hours. My server dates are stored as a DateTime field, should these be DateTimeOffsets instead?

Also, is there a way to simply tell the server to treat all dates read from the database as UTC and not Local?

**Comment by jmichas** [comment]
So, as a follow up, I expanded my test from the linked issue above and added a DateTimeOffset field.
After posting to the server and using swagger to retrieve the record I get this:
```
{
  "deleted": false,
  "updatedAt": null,
  "createdAt": "2016-05-08T20:54:53.533Z",
  "version": "AAAAAAANlYA=",
  "id": "c771964178d247a1a7a9481e079134e7",
  "dateTimeUtcOffset": "2016-05-08T20:54:49.226Z",
  "dateTimeLocal": "2016-05-09T00:54:49.227Z",
  "dateTimeUtc": "2016-05-09T00:54:49.227Z"
}
```
You can see that the DateTimeUtc and DateTimeLocal have been shifted +4, the CreatedAt and DateTimeUtcOffset are the correct date time as created on the client. All 3 fields display the same date and time in SQL Server. So, when the mobile app server controller is serializing (I think) it is treating the value as Local so it adds 4 hours. The offset one stays the same since it explicitly tells that the offset it +0.

So, how can I tell the server to treat the DateTimes as UTC and serialize them properly? I would rather not have to go a change all my datetime fields to offsets and then rework all my client code to deal with them. I just want to add that in Mobile Services this was not an issue. The client and server projects were upgraded from the older retired Mobile Services. There should be something about DateTime in the upgrade documentation because this has become a major issue for me.

**Comment by brettsam** [comment]
Let me restate the issue so that I can try to reproduce this -- in Mobile Services you had an Entity Framework model with a `DateTime` property. This always returned UTC time. But now in Mobile Apps that same `DateTime` property now treats this as local when you request it, which shifts it with each request. Is that accurate? 

If that's the case, can you share your Web API setup code? -- are you setting up any serializers or doing anything special with EF other than the default?

**Comment by jmichas** [comment]
@brettsam Yes, that is the problem. My WebApi setup is the default, I did not do anything with the serializers or EF.

In any event, I have since changed all my DateTimes to DateTimeOffsets on my client and server since I wasn't sure if there was a solution for the problem. But this is something that should either be fixed or at least addressed in the upgrade and/or general documentation. There isn't much info out there on DateTime handling on the client or server.

**Comment by adrianhall** [comment]
Our recommendation is to use DateTimeOffset as DateTime is automatically converted by the runtime on output, which is what you are seeing.  You should always use DateTimeOffset in the server.

Closing - feel free to re-open if this does not fix your issue.

**Comment by austinemser** [comment]
@adrianhall What if you don't have control over the existing column? ie. you are forced to use a DateTime in SQL server.

**Comment by adrianhall** [comment]
Then (a) live with the output and the problems, or (b) fix the table.  Those are your two choices.
