### ISSUE TITLE
System.IdentityModel.SignatureVerificationFailedException when trying to call a google authenticated Azure WebApp

### ISSUE THREAD

**Issue by hemhedge** [Azure/azure-mobile-apps-net-server#127]
I have deployed a web App on Azure and calling the API from a xamarin app. I have set up google authentication. seems like initial google sign-in works fine, but the api call fails with the SignatureVerificationFailedException.
here is the logs:
Microsoft.Azure.AppService.Authentication Verbose: 0 : Received request: GET https://XXXX.azurewebsites.net/login/done
Microsoft.Azure.AppService.Authentication Verbose: 0 : Found 'AppServiceAuthSession' cookie for site 'XXXX.azurewebsites.net'. Length: 640.
Microsoft.Azure.AppService.Authentication Verbose: 0 : Authenticated XXXXXXX@gmail.com successfully using 'Session Cookie' authentication.
Microsoft.Azure.AppService.Authentication Verbose: 0 : Received request: GET https://XXXXXX.azurewebsites.net/favicon.ico
Microsoft.Azure.AppService.Authentication Verbose: 0 : Found 'AppServiceAuthSession' cookie for site 'XXXXX.azurewebsites.net'. Length: 640.
Microsoft.Azure.AppService.Authentication Verbose: 0 : Authenticated XXXXXX@gmail.com successfully using 'Session Cookie' authentication.
Microsoft.Azure.AppService.Authentication Verbose: 0 : Received request: GET https://XXXXXXX.azurewebsites.net/api/getUserIdentity
Exception thrown: 'System.IdentityModel.SignatureVerificationFailedException' in Microsoft.Azure.AppService.Authentication.dll
Microsoft.Azure.AppService.Authentication Warning: 0 : JWT validation failed: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.InMemorySymmetricSecurityKey
'.
Exceptions caught:
 ''.
token: '{"typ":"JWT","alg":"HS256"}.{"iss":"urn:microsoft:windows-azure:zumo","aud":"urn:microsoft:windows-azure:zumo","nbf":146XXXXX,"exp":146XXXXX,"urn:microsoft:credentials":"{}","uid":"Google:XXXXXXXXXXXXX","ver":"2"}
RawData: XXXXXXXXXXX.XXXXXXXXX.bs9-XXXXX'.
Microsoft.Azure.AppService.Authentication Information: 0 : Sending response: 401.71 Unauthorized
I have deployed a web App on Azure and calling the API from a xamarin app. I have set up google authentication. seems like initial google sign-in works fine, but the api call fails with the SignatureVerificationFailedException.
here is the logs:
Microsoft.Azure.AppService.Authentication Verbose: 0 : Received request: GET https://XXXX.azurewebsites.net/login/done
Microsoft.Azure.AppService.Authentication Verbose: 0 : Found 'AppServiceAuthSession' cookie for site 'XXXX.azurewebsites.net'. Length: 640.
Microsoft.Azure.AppService.Authentication Verbose: 0 : Authenticated XXXXXXX@gmail.com successfully using 'Session Cookie' authentication.
Microsoft.Azure.AppService.Authentication Verbose: 0 : Received request: GET https://XXXXXX.azurewebsites.net/favicon.ico
Microsoft.Azure.AppService.Authentication Verbose: 0 : Found 'AppServiceAuthSession' cookie for site 'XXXXX.azurewebsites.net'. Length: 640.
Microsoft.Azure.AppService.Authentication Verbose: 0 : Authenticated XXXXXX@gmail.com successfully using 'Session Cookie' authentication.
Microsoft.Azure.AppService.Authentication Verbose: 0 : Received request: GET https://XXXXXXX.azurewebsites.net/api/XXXXXX
Exception thrown: 'System.IdentityModel.SignatureVerificationFailedException' in Microsoft.Azure.AppService.Authentication.dll
Microsoft.Azure.AppService.Authentication Warning: 0 : JWT validation failed: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.InMemorySymmetricSecurityKey
'.
Exceptions caught:
 ''.
token: '{"typ":"JWT","alg":"HS256"}.{"iss":"urn:microsoft:windows-azure:zumo","aud":"urn:microsoft:windows-azure:zumo","nbf":146XXXXX,"exp":146XXXXX,"urn:microsoft:credentials":"{}","uid":"Google:XXXXXXXXXXXXX","ver":"2"}
RawData: XXXXXXXXXXX.XXXXXXXXX.bs9-XXXXX'.
Microsoft.Azure.AppService.Authentication Information: 0 : Sending response: 401.71 Unauthorized

**Comment by adrianhall** [comment]
You are using the old SDK with the new server.  Update your .NET client.
