### ISSUE TITLE
It is not possible to add a reference to Shared Project

### ISSUE THREAD

**Issue by jiberan** [Azure/azure-mobile-apps-net-server#128]
It is not possible to add a reference to Shared Project. List of shared projects is missing in add reference dialog.

**Comment by adrianhall** [comment]
Can you please identify how you are building the project?  What is your starting point and what are you trying to do?

**Comment by jiberan** [comment]
I was trying to share project with DTOs betweet server and Xamarin mobile app.

**Comment by adrianhall** [comment]
Understood.  We'll keep this on the backlog, but it's unlikely to get a high priority.

**Comment by jiberan** [comment]
What is now considered as best practice to sharing DTOs between client and server?

**Comment by adrianhall** [comment]
I don't think you should.  There are several reasons why the client and server should be different.  Your client models don't need createdAt and deleted fields, for example, which are in EntityData.  EntityData is for Entity Framework, which doesn't exist on the client side.  You can also release server and client independently (and you can't guaranteee that clients are up to date).  Lots of reasons why the client and server are different.

I'd create an interface for the model fields, then implement the concrete version on each side independently.  That way, the models are kept in sync (or at least build-time errors occur when they aren't in sync).

**Comment by adrianhall** [comment]
Just to not keep people in suspense and to provide transparency, we will not be completing this work.  Architecturally, it doesn't make sense and is a big change with little advantage.
