### ISSUE TITLE
Add priority to GooglePushMessage class

### ISSUE THREAD

**Issue by edorphy** [Azure/azure-mobile-apps-net-server#132]
https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message

The values are "high" and "normal" and the key is "priority" at the parent level.

**Comment by adrianhall** [comment]
We are deprecating the NotificationsController in favor of the App Service integrated push registration controller.  As a result, this won't be fixed in the server code.

**Comment by edorphy** [comment]
Adrian,

I couldn't find any references to a push registration controller. Is there API documentation available for this? I also didn't notice any deprecated updates in GitHub, do you know when this will be available?

**Comment by adrianhall** [comment]
We are working on the documentation, but it is available right now.  It's enabled within the Push menu option of your App Service.
