### ISSUE TITLE
Add support for the Notification payload in GooglePushMessage

### ISSUE THREAD

**Issue by edorphy** [Azure/azure-mobile-apps-net-server#133]
For iOS there exists the AlertProperties, but there is no equivalent built in for Google's Notification dictionary and its predefined keys.

See the keys defined for Android here: https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support

**Comment by adrianhall** [comment]
The NotificationsController is now in-built into the App Service and no longer a part of the SDK.

**Comment by edorphy** [comment]
Adrian,

Can you clarify what is meant by "in-built into the App Service"? I haven't seen any documentation for removal of the NotificationController. You mentioned it was deprecated in another closed feature request.

The intent of my original feature request was not bound or related to the NotificationController but rather the PushClient with corresponding IPushMessage interface and respective classes. These are all found in the Microsoft.Azure.Mobile.Server.Notifications Nuget package as part of the SDK. Are these also being removed from the SDK?

**Comment by adrianhall** [comment]
App Service has a built-in feature for push registration - you can turn it on within the Azure Portal by going to the "Push" menu option.  This replaces (and is better than) the NotificationsController.
