### ISSUE TITLE
AppServiceLoginHandler CreateToken lifeTime not respected

### ISSUE THREAD

**Issue by FrancoisM** [Azure/azure-mobile-apps-net-server#137]
For some expiring token tests I've setup the lifetime of my token to 20 sec. However, after more than 20 sec being logged in, I still don't get Unauthorized access to my api requests.
It does happen but It takes longer (a few minutes).

**Comment by brettsam** [comment]
I believe that App Service Authentication has a window of several minutes for honoring the timeouts. @cgillum may be able to give you the exact answer.

**Comment by FrancoisM** [comment]
My issue is that tokens don't expire as soon as they should. My request do return. No timeouts, no 401.

**Comment by cgillum** [comment]
There is a 5 minute grace period for expired tokens to account for clock skew. That would be why your tokens are still being accepted after the 20 seconds.

**Comment by FrancoisM** [comment]
Ok makes sense now.
Tks @cgillum
