### ISSUE TITLE
Expired AccessToken and Refresh token is empty for Microsft and Google identity providers

### ISSUE THREAD

**Issue by danielloczi** [Azure/azure-mobile-apps-net-server#14]
Microsoft and Google Access Tokens (which were returned by the Azure gateway, and can be used to make api calls in the name of the logged in user) can be expired after some amount of time. In that case, based on the documentation we should use the the Refresh token to request a new Access Token. 
Unfortunately I'm experiencing a problem, that the Refresh Token is empty. I was able to narrow down the problem to the `GetRawTokenAsync()` method inside `AppServiceHttpClient.cs`. It seems that the request to the gateway doesn't return any refresh token:

```csharp
Uri requestUri = new Uri(this.gatewayUri, "/api/tokens?tokenName={0}&api-version={1}".FormatInvariant(tokenName, ApiVersionValue));
```
The gateway api version is `"2015-01-14"`

So finally I have a broken major functionality, and I have no idea how to solve this problem. :( 

Can you help me please?
Is there another api call to the gateway to get a Refresh Token? 
Is there a documentation about Azure gateway?

Any help is appreciated! Thanks in advacance!

**Comment by mattchenderson** [comment]
There are a few changes coming which will start surfacing this value. We're working on modifying the getIdentityAsync method to accommodate those API changes. Until then, unfortunately this is a limitation of the gateway.

**Comment by brettsam** [comment]
I don't believe it is documented anywhere (yet) but you can tell Google to send Refresh tokens by:

1. In the Azure portal, select your Mobile App
2. Click on the Resource Group that your Mobile App belongs to
3. Select the Gateway
4. In the 'Essentials' box, click the Gateway host.
5. In your Gateway host's Application Settings pane, under *App settings*, add `MS_GoogleAccessType` with a value of `offline`. You should already see some other `MS_` values there that correspond to your identity provider ids and secrets

Login from your client again to force Google to supply a refresh token, then use GetIdentitiesAsync<GoogleCredentials>() again. Now you should have a RefreshToken value in your GoogleCredentials.

As Matthew said, this will get easier in the future, but hopefully this unblocks you.

**Comment by danielloczi** [comment]
Thank you for the feedback! I tried it, and seems okay!
After configuring `MS_GoogleAccessType`, users have to approve "offline access". After that, if a user hits okay, the gateway will give you a refresh token. Using this token you can write your own code to get a new access token if you need it,  This is a kind of a workarond, but works well to me. Thanks!

What is the plan for the future?
I beleive Mobile App (Gateway) should handle this scenario in the background and should make this refresh token thing to fully transparent for the developers.

**Comment by brettsam** [comment]
This issue is specifically referencing the Gateway, which has been replaced by App Service Authentication. 

But -- @cgillum has written a [great blog post](http://cgillum.tech/2016/03/07/app-service-token-store/) documenting the token store. It explains how to use the new App Service Authentication feature for refreshing tokens (see the **Refreshing Tokens** section). There is a specific code sample there for Mobile Apps.
