### ISSUE TITLE
Facebook Graph Version

### ISSUE THREAD

**Issue by chadiswar** [Azure/azure-mobile-apps-net-server#143]
Looking for some clarification.  I received a message regarding my Facebook application I have registered at developers.facebook.com.  This is the application I have configured for only authentication with my App Services mobile app using the latest SDK.  The message warns:

> "app_name has been making recent API calls to Graph API v2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences.
> We recommend using our new Graph API Upgrade Tool to see which of your calls are affected by this change as well as any replacement calls in newer versions. You can also use our changelog to see the full list of changes."

Some more information, this is the same facebook app that was used for my old ASP.Net website and the OWIN framework for Facebook authentication.  This site was discontinued about 4 months ago to begin development on the new App Services framework.  Could this email be regarding the old site's graph calls?  Also, is there a way to verify - or is it known - which version of FB Graph that App Service SDK uses?

Thanks in advance.

Chad

Edit, I wanted to add that the only scope items I have selected in the Azure portal authentication configuration are "public_profile, user_friends, email".  I am not doing any custom scopes or requests, just basic authentication.

**Comment by adrianhall** [comment]
We don't actually specify any version information to the Facebook Graph API calls we make.  Facebook implicitly sets a version.  If you go to https://developers.facebook.com and log in, select your app, then Dashboard, you will see the default version number listed.  In your case, it is 2.0.  In my case (a newer app, obviously), it's 2.8.  My app works as expected.

You will need to work with Facebook directly to work out how to change the default version to v2.8.
