### ISSUE TITLE
Issues with StorageDomainManager

### ISSUE THREAD

**Issue by josesimoes** [Azure/azure-mobile-apps-net-server#150]
I'm trying to use the StorageDomainManager and I'm having issues with:
- LookupAsync: throws the following exception
  "message": "An error has occurred.",
  "exceptionMessage": "Método não encontrado: 'Microsoft.WindowsAzure.Storage.Table.TableOperation Microsoft.WindowsAzure.Storage.Table.TableOperation.Retrieve(System.String, System.String)'.",
  "exceptionType": "System.MissingMethodException",
  "stackTrace": "   em Microsoft.Azure.Mobile.Server.StorageDomainManager`1.<GetCurrentItem>d__27.MoveNext()\r\n   em System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\r\n   em Microsoft.Azure.Mobile.Server.StorageDomainManager`1.GetCurrentItem(CompositeTableKey key, Boolean includeDeleted)\r\n   em Microsoft.Azure.Mobile.Server.StorageDomainManager`1.<LookupItemAsync>d__c.MoveNext()\r\n--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Azure.Mobile.Server.StorageDomainManager`1.<LookupAsync>d__8.MoveNext()\r\n--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Azure.Mobile.Server.TableController`1.<LookupAsync>d__0.MoveNext()"
- QueryAsync.: doesn't return any results

I only get that exception with using WindowsAzure.Storage above 6.2.0. For 6.2.0 and bellow that doesn't happen.

**Comment by josesimoes** [comment]
I've pulled the code from GitHub and tried to figure out the answers to my own questions.
Here's what I've found.

On the first issue: using the StorageDomainManager code from GitHub there is no issue when referencing WindowsAzure.Storage 7.0 and above. I guess this has already been fixed.

On the second: 
In the table controller Initialize() method, when instantiating the StorageDomainManager, enableSoftDelete has to be FALSE, not true has you have on the example app.
If the enableSoftDelete is set to true an extra filter (Deleted ne true) is added to the Table Storage query operation. If there is no 'Deleted' row in the storage table being queried the query operation alwys returns 0 elements.
My suggestions:
- Clearly stating in the documentation that that 'Deleted' row needs to exist on the table storage if the user wants to make use of the soft delete feature.
- Changing the example app to have enableSoftDelete set to false and adding a comment there stressing what would already be on the documentation regarding that.


Questions:
- Are you planning to release a new Nuget package anytime soon? Even a pre-release or RC would be great. The last one dates from January and a lot has changed since then...
- Do you have any plans to make available "nightly builds" or more frequent pre-release Nuget packages? That would allow the community to test new features and changes and provide feedback about those.

**Comment by brettsam** [comment]
Thanks for the feedback @josesimoes. Some responses:
- The documentation and sample suggestions are good. I'll leave this issue open to track those items.
- I've set up a feed on myget.org with a daily build that has the latest changes. I haven't documented it anywhere (yet) but please give it a try. The SLA for this feed will be something like "Use at your own risk. These packages have passed all unit tests but may not have had any testing past that." If you find any issues there, please let us know. The feed info:
    - Nuget v3: https://www.myget.org/F/azure-mobile/api/v3/index.json
    - Nuget v2: https://www.myget.org/F/azure-mobile/api/v2
- I agree with the "daily build" releases. We'll use the myget feed for that.

**Comment by josesimoes** [comment]
@brettsam awesome!
I'm quite all right with that SLA (wasn't expecting anything much different 😉 ) and will give it a try.

**Comment by ruttopia** [comment]
Any updates on when we might see an official Nuget package release?

Thanks!
Mike

**Comment by adrianhall** [comment]
Ref: #164 - we are doing a set of work now to update all the packages to their latest and greatest and updating to 4.6.1 .NET Framework as the base.

**Comment by adrianhall** [comment]
Closing this issue now as we are in the final process to release the next v2.0.0 of the server.  Blog post will be forthcoming as well.
