### ISSUE TITLE
Request for MappedStorageDomainManager

### ISSUE THREAD

**Issue by josesimoes** [Azure/azure-mobile-apps-net-server#151]
I was trying to use AutoMapper with the StorageDomainManager without success.
It seems that there is no call to ProjectTo to make the mapping magic to happen.

Question: would you consider a "MappedStorageDomainManager" to be added to make this possible?

**Comment by adrianhall** [comment]
Hi @josesimoes - The StorageDomainManager doesn't have a concept of mapping available to it as it is a pass-thru OData feed.   We are also not intending on doing any further work on the StorageDomainManager.
