### ISSUE TITLE
Moving from gateway authentication

### ISSUE THREAD

**Issue by martinoss** [Azure/azure-mobile-apps-net-server#152]
I migrated my azure mobile service to mobile apps about a year ago. At this time, azure created an authentication gateway for me. I considered the "uid" in the token as stable user id. 
Now I want to migrate to app service authentication and I am faced with the problem, that neither the "sid" nor the "stable_sid" matches the uid I get from the authentication gateway when login the the same provider account.

Any advice, how I should do the transition? How has the old "uid" been generated?

**Comment by lindydonna** [comment]
See https://github.com/Azure/azure-mobile-apps-net-server/wiki/Understanding-User-Ids
