### ISSUE TITLE
MicrosoftAccount returning sid:00000000000000000000000000000000

### ISSUE THREAD

**Issue by MartinZikmund** [Azure/azure-mobile-apps-net-server#155]
I have not yet been able to completely isolate the issue, but trying to authenticate with Microsoft Account using `MobileServiceClient.LoginAsync` method, the app service sometimes returns a `MobileServiceUser` instance, that has `UserId`of `sid:00000000000000000000000000000000`. The interesting thing about it is that it does not happen for all accounts, some have their ID returned correctly.

**Comment by MartinZikmund** [comment]
Also on the server-side, in such case the same ID is returned with:
`string userId = ( User as ClaimsPrincipal).FindFirst( ClaimTypes.NameIdentifier ).Value;`

**Comment by jamesmontemagno** [comment]
have you checked out: https://github.com/Azure/azure-mobile-apps-net-server/wiki/Understanding-User-Ids with stable_id?

**Comment by adrianhall** [comment]
@MartinZikmund Do you have a github repo that has a repo of this?  I can't reproduce when the MSA is configured correctly.

**Comment by adrianhall** [comment]
Based on a lack of comment from the OP, closing for now.  It can be re-opened if still a problem.
