### ISSUE TITLE
Add login support for SFSafariViewController by having .auth/login/<provider> redirect to app

### ISSUE THREAD

**Issue by edorphy** [Azure/azure-mobile-apps-net-server#156]
Feature Request: 
https://developer.apple.com/videos/play/wwdc2015/504/ Minute 24.

Apple shows how you can security do OAuth using SFSafariViewController introduced in iOS 9.

Provide the myWebsite ... /.auth/login/provider to the Safari view controller and away you go. 

Benefits:
No dependency on the MS Client SDK. 
Secure Safari (no way for app to steal data from Webkit view
Safari saved passwords

**Comment by edorphy** [comment]
Google is going to drop OAuth support for UIWebView "in the near future".

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by chadiswar** [comment]
Do we have any more information from the app services team about the impact of this change?  My company has an iOS and Android app built around the app services authentication which is too be released in the next couple weeks and I need to make a recommendation regarding to delay it or not.

Thanks,

Chad

**Comment by edorphy** [comment]
Any updates?

This link from google states new apps will not support web view OAuth after October 20th. Thats a week away! My application isn't in production and I don't have the prod google credentials stuff setup yet. I will likely fall into this "new app" category if I understand Google's meaning.

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-ios-client/issues/90#issuecomment-256748256 explains the details of the fix for this issue for iOS. Android implementation will be on similiar lines, but using Custom Chrome tabs. In the short term, you should consider using client flow for authentication.

**Comment by adrianhall** [comment]
Closing this as it is not a server issue - it is a client SDK issue primarily.  We've got issues in progress for the Google OAuth SDK updates in each server.
