### ISSUE TITLE
Missing Tag copy

### ISSUE THREAD

**Issue by mbharodia** [Azure/azure-mobile-apps-net-server#162]
azure-mobile-apps-net-server/src/Microsoft.Azure.Mobile.Server.Notifications/Controllers/NotificationInstallationsController.cs 

at line 18 

"Installation" type is generated from "NotificationInstallation". This method, looks like that, does not copy "Tags" property from "NotificationInstallation". 

Please check. If I am missing something, then please let me know and accept my apology. 

I am using this package and it does not copy tags. I was locating a problem and I am not able to find anything except this method where there is no code to copy "Tags" supplied in "NotificationInstallation" object.

**Comment by mbharodia** [comment]
Please read line #82  instead of #18

**Comment by adrianhall** [comment]
We explicitly do not allow tags in the registration service.  Use the App Service Push registration endpoint instead, as that allows tags.
