### ISSUE TITLE
Support .NET Framework 4.6 as a base version

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-net-server#164]
We need to update all the libraries within the Azure Mobile Apps Server packages.

Update all references in Azure Mobile Apps Server SDK to latest versions
Make .NET Framework 4.6.0 the minimum version
Update the version number for the Mobile Apps SDK to be 2.0.0

**Comment by tofutim** [comment]
Out of curiosity, what is the impetus for making 4.6 the minimum version?

**Comment by adrianhall** [comment]
As part of upgrading the overall infrastructure to support later libraries, we also wanted to ensure we supported the latest version of .NET Framework that was pre-.NET Core.
