### ISSUE TITLE
Enabling Authentication with SIgnalR against Azure Mobile Services when debugging on localhost

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-server#165]
Hi, I'm really struggling with debugging my zumo+signalr hubs. When debugging in localhost, signalr is always unauthenticated even if I have the x-zumo-auth header set. Probably because my localhost is not running anything that can change that into an identity. However, the zumo stuff works using the AlternateLoginHost trick. Can someone provide some tips for me? SO link below.

http://stackoverflow.com/questions/40033175/enabling-authentication-with-signalr-against-azure-mobile-services-when-debuggin

**Comment by adrianhall** [comment]
This SDK does not deal with SignalR, so it's out of scope for this repo.  I'll take a look at the SO question though.
