### ISSUE TITLE
Using DocumentDb C# SDK on the backend

### ISSUE THREAD

**Issue by nhwilly** [Azure/azure-mobile-apps-net-server#168]
I know I saw somewhere that you couldn't use the SDK, but now I can't find the reference or the reason, so I thought I'd ask here to memorialize the answer.

I don't have to have full integration like a TableController or anything like that.  I just want to develop a repository component and use it to access DocumentDb using the SDK.  

I couldn't get it to work originally, so I developed a REST component.  It failed, too but since then I've learned a lot more about async/await.  I fixed my REST problems and it's working, but I'd still like to use the SDK going forward.

So I know that DocDb is being worked on, but I don't know what integration is planned.

Is it still true that it doesn't work under any circumstances?  If there's something really fundamental that's a show stopper, I'll just continue to use the REST stuff I did.

I upgraded everything to 4.6.1, btw.

TIA.

**Comment by adrianhall** [comment]
It's really fundamental and comes down to two things:

1) System.Web.OData (which is the underlying transport wire protocol) does an implicit `ORDER BY id` to ensure that the same ordering of records is retrieved each time.  DocumentDb does not allow `ORDER BY id`.
2) System.Web.OData then does another order by for multiple ORDER BY if one is required.  DocumentDb does not allow multiple ORDER BY clauses.

Until these two issues are fixed, our hands are tied by the System.Web.OData library being fundamentally incompatible with DocumentDb. 

The DocumentDb team are aware of these issues.  Just go with a direct DocumentDb connection right now.  I would only use the app service backend for generating / retrieving appropriate keys for access.

**Comment by nhwilly** [comment]
Very helpful as always, Adrian.

I'll just work with my REST code for now.  And I just finished the REST code for getting permissions from DocumentDb for a user.

But since this is a financial app, I'm not letting anyone write to the database from an unsecured client.

I tested my REST code on the Xamarin Forms side and it works great there, too.

You response is very much appreciated.

**Comment by gorillapower** [comment]
Does DocumentDB support this now? It looks like it from the documentation here https://github.com/Microsoft/azure-docs/blob/master/articles/documentdb/documentdb-orderby.md
