### ISSUE TITLE
Microsoft.Azure.Mobile.Server.Authentication nuget package constraint to JWT

### ISSUE THREAD

**Issue by willduarte** [Azure/azure-mobile-apps-net-server#169]
I found a problem trying to implement authentication on .NET server.

Basically, the [Microsoft.Azure.Mobile.Server.Authentication](https://www.nuget.org/packages/Microsoft.Azure.Mobile.Server.Authentication) nuget package has a dependency to **System.IdentityModel.Tokens.Jwt (>= 4.0.2.205111437)**.

But in the current version of **System.IdentityModel.Tokens.Jwt** (5.0.0) has incompatibility between classes on **AppServiceLoginHandler.CreateToken** method.

For now I downgraded to the **4.0.3.308261200** version of JWT, but, or the nuget package constraint need to be changed or the next version of **Microsoft.Azure.Mobile.Server.Authentication** need to have compatibility with JWT 5.0.0.

PS1: I'm in on the alpha channel, but the constraint is the same on the stable channel.

**Comment by adrianhall** [comment]
The System.IdentityModel.Tokens.Jwt has this issue all over the place.  It is only valid for .NET Core.    What the system is saying is "use the latest version of ...Jwt that is compatible with our runtime", but the runtime match was left out of the Jwt packaging.

You've done the right fix.
