### ISSUE TITLE
Mobile Apps Swagger NuGet package not available

### ISSUE THREAD

**Issue by tylerd** [Azure/azure-mobile-apps-net-server#171]
According to this page there was a vulnerability in Swagger UI
https://github.com/Azure/azure-mobile-apps-net-server/wiki/Adding-Swagger-Metadata-and-Help-UI-to-a-Mobile-App

but now it seems that the XSS has been fixed, is there any reason that the NuGet package is still pulled?
https://www.nuget.org/packages/Microsoft.Azure.Mobile.Server.Swagger

**Comment by adrianhall** [comment]
See PR #153

**Comment by pvbchak** [comment]
Released in https://www.nuget.org/packages/Microsoft.Azure.Mobile.Server.Swagger/2.0.0
