### ISSUE TITLE
Malfunction of App Service PUSH (Azure Portal Blade)

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-server#178]
Hi,

Today I switched my Mobile App Backend to utilize the App Service PUSH. 

These are a steps I did to activate the App Service Push:

1.	In Azure Portal –> Settings -> App Settings removed the MS_NotificationHubName=hubname key-value pair and MS_NotificationHubConnectionString=hub-connectionstring 
2.	In Azure Portal -> Settings -> Push -> selected Connect

After testing if the push notification still works I noticed that the `_UserId` now contains an unknown value like that:

![hub_app_service_push](https://cloud.githubusercontent.com/assets/6480047/21957464/df24bd12-da96-11e6-8788-d7e795ed159b.png)

Before I switched to App Service Push I got the JWT.Sub (NameIdentifier) set as my `_UserId` like that:

![hub_app_service_push_2](https://cloud.githubusercontent.com/assets/6480047/21957480/4f2f1ae4-da97-11e6-8906-3e3e020361cd.png)

In my CustomAuthController I set the IMEI to the JWT.Sub like that:

        [HttpPost]
        public async Task<IHttpActionResult> Post([FromBody] JObject assertion)
        {
            var imei = assertion[ImeiKey]?.ToString()?.Trim();

            var truckFahrer = await GetTruckFahrerForImei(imei);

            if (truckFahrer == null)
            {
                return Unauthorized();
            }
            
            
            var claims = new Claim[]
            {
                new Claim(JwtRegisteredClaimNames.Sub, imei),
                new Claim(TruckFahrer.FahrerBezKey, truckFahrer?.FahrerBez ?? string.Empty),
                new Claim(TruckFahrer.FahrerNameKey, truckFahrer?.FahrerName ?? string.Empty), 
                new Claim(TruckFahrer.FahrerVornameKey, truckFahrer?.FahrerVorname ?? string.Empty),
                new Claim(TruckFahrer.FahrerHandyNrKey, truckFahrer?.FahrerHandyNr ?? string.Empty),   
                new Claim(TruckFahrer.FahrerIdKey, truckFahrer?.FahrerId.ToString()),
                new Claim(TruckFahrer.SprachIdKey, truckFahrer?.SprachId.ToString()),
                new Claim(TruckFahrer.TruckFirmaNameKey, truckFahrer?.TruckFirmaName ?? string.Empty)
            };

            // see: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/debugging/
            if (!string.IsNullOrWhiteSpace(Configuration.GetMobileAppSettingsProvider().GetMobileAppSettings().HostName))
            {
                // In Azure Portal HostName is not null
                _signingKey = Environment.GetEnvironmentVariable("WEBSITE_AUTH_SIGNING_KEY");
                var website = Environment.GetEnvironmentVariable("WEBSITE_HOSTNAME");
                _audience = $"https://{website}/";
                _issuer = $"https://{website}/";
            }
            else
            {
                // on IIS local debugging HostName is null. Make sure HostName is not set in Web.config
                _signingKey = Configuration.GetMobileAppSettingsProvider().GetMobileAppSettings()["SigningKey"];
                _audience = Configuration.GetMobileAppSettingsProvider().GetMobileAppSettings()["ValidAudience"];
                _issuer = Configuration.GetMobileAppSettingsProvider().GetMobileAppSettings()["ValidIssuer"];
            }

            var token = AppServiceLoginHandler.CreateToken(claims, _signingKey, _audience, _issuer, TimeSpan.FromDays(30));

            return Ok(new LoginResult()
            {
                AuthenticationToken = token.RawData,
                User = new LoginResultUser {UserId = imei}
            });
        }

That code works.

In November 2016 I posted a similar issue : [Not working Register Push](https://github.com/Azure/azure-mobile-apps-net-server/issues/170#issuecomment-262656329) which got closed but the issue still exists.

Thanks for any help.
Erich

**Comment by ericbrunner** [comment]
@@jwallra Do you have any idea or do I have to add an UpdateTagsController and add my client Tag that way like described here: https://blogs.msdn.microsoft.com/writingdata_services/2016/01/22/adding-push-notification-tags-from-an-azure-mobile-apps-client/

**Comment by adrianhall** [comment]
As I have (unfortunately, repeatedly) said, you have to do your own registration if you are doing custom auth with auth-based tags.  The App Service Push works only with the ones that work with App Service Authentication/Authorization.   There are several sources for this information, but basically you need to write a custom API to register your client (based on deviceToken and authenticated claims) with Notification Hubs using the NH SDK.

**Comment by ericbrunner** [comment]
@AdrianHall Nowhere is mentionef that the UserId gets MD5 hashed with App Service Push. ANYWAY, in the meanwhile I have the solution with the UpdateTagsController in my backend.
