### ISSUE TITLE
Update of Azure Server SDK v.2.0.0 in Mobile App backend targeting FW 4.5.2. not possible

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-server#179]
Hi,

Today I wanted to update from Microsoft.Azure.Mobile.Server v1.1.157.1 to Server SDK v2.0.0 but failed with that message:

> Could not install package 'Microsoft.Azure.Mobile.Server 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			

How can I update the Server SDK?

Thanks,
Eric

**Comment by ericbrunner** [comment]
After targeting to FW 4.6 and not FW 4.6.1 it worked. But I have 3 remaining packages that causes compilation errors when I attempt to update and recompile:

![remaining_update_packages](https://cloud.githubusercontent.com/assets/6480047/22138302/2790b720-dee0-11e6-9013-b653c9311383.jpg)

at that line in my CustomAuthController

`var token = AppServiceLoginHandler.CreateToken(claims, _signingKey, _audience, _issuer, TimeSpan.FromDays(30));`

Show I stick with that versions ?

**Comment by adrianhall** [comment]
v2.0.0 deliberately re-targetted so that we could progress and keep pace with the updates in dependent packages.

You can update Microsoft.* - however, System.IdentityModel.Tokens.Jwt v5.x is for .NET Core and not compatible with the SDK.  So leave that one alone.

**Comment by ericbrunner** [comment]
@AdrianHall Thanks, I will leave System.IdentityModel.Tokens.Jwt on v.4.*  and update the rest.
