### ISSUE TITLE
[Azure.Mobile.Server.Login] AppServiceLoginHandler.CreateToken can't find type JWTSecurityToken 

### ISSUE THREAD

**Issue by austinemser** [Azure/azure-mobile-apps-net-server#181]
when trying to call AppServiceLoginHandler.CreateToken, i am getting the compiler error 

Reference to type 'JwtSecurityToken' claims it is defined in 'System.IdentityModel.Tokens.Jwt', but it could not be found

(code was taking directly from https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/custom/) on class Controllers\CustomAuthController.cs

**Comment by pvbchak** [comment]
Can you please check version of System.IdentityModel.Tokens.Jwt nuget package. 5.* version of System.IdentityModel.Tokens.Jwt is only supported on .net core & not on .net 4.6. If that is true, please downgrade it to 4.0.3 version.

**Comment by adrianhall** [comment]
No response, so I'm going to assume this was the answer.  If it isn't, please provide more information and re-open.

**Comment by filoe** [comment]
This is still a problem. I'm on .net 4.6.

**Comment by adrianhall** [comment]
What version of System.IdentityModel.Tokens.Jwt do you have installed?

**Comment by pablotdv** [comment]
What's the solution for this issue?

My version of System.IdentityModel.Tokens.Jwt is 5.1.3.

The poblem is:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7069	Reference to type 'JwtSecurityToken' claims it is defined in 'System.IdentityModel.Tokens.Jwt', but it could not be found	Backend	d:\develop-mobile-apps-with-csharp-and-azure\Chapter1\Backend\Controllers\CustomAuthController.cs	47	Active

**Comment by fileman** [comment]
@pablotdv Jwt version must be 4.x !
5.x is for asp.net core

**Comment by roxanabeloiu** [comment]
Version 4.0.40306.1554 worked for me for .NET Framework 4.6

**Comment by vackup** [comment]
Cool!! now is working!
