### ISSUE TITLE
Add support for System.IdentityModel.Tokens.Jwt >= 5.0.0

### ISSUE THREAD

**Issue by InquisitorJax** [Azure/azure-mobile-apps-net-server#185]
There was a breaking namespace change in the System.IdentityModel.Tokens.Jwt nuget package from release 5.
see: https://forums.xamarin.com/discussion/79135/error-using-jwtsecuritytoken

**Comment by tofutim** [comment]
I also ran into this today. The interim fix is to jump back to 4.0.3.* but who wants to do that.

**Comment by adrianhall** [comment]
@tofutim, System.IdentityModel.Tokens.Jwt 5.x nugets are only supported with ASP.NET Core 1.x (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/README.md#usage).

Mobile Apps .Net Server SDK is not supported on ASP.NET Core & so have to revert back to System.IdentityModel.Tokens.Jwt 4.x.

**Comment by kjmbutu** [comment]
@adrianhall, your comment is one of the reasons I hate programming. It is perfectly normal for someone to want to update to the latest versions of NuGet packages out there. But then when it doesn't work you reference a page where it states that that combination is not allowed anymore. No reason, no known impact for other project/dependencies. It just is now. You didn’t know what? Wow, you should have read that dummy!

You could have gone another route where it was backwards compatible. Or just start a new project/nuget package for Core. 

I know you don’t do this intentionally, but you are making programming more complex by adding all of these little quirks. It really obfuscates what programming is here for. It should become simpler over time to build larger applications to help (mostly non-technical) end users. But we never seem to get there.
I know what you are probably thinking: you should not be a developer! You are right, I probably shouldn’t be. I certainly don’t want to be when I deal with something like for the x-th time. But most people go to work every day and have really mundane projects where most people don’t care about all this technical mumbo jumbo. We are there to get things done. Where time is money and everything is always too late. So it would be great if for once in a while I would not have to spent 15 minutes finding out why I couldn’t just update all of my nuget packages in my project. I know my colleagues will be wondering that in the near future as well.

p.s. I wrote this in my spare time :)

**Comment by adrianhall** [comment]
I hear you - it's frustrating having to track these various dependencies.  I'd love to live in a world where we don't take dependencies and everything is perfectly backwards compatible.   Reality is that this is why people DON'T update beyond a major version once it is working unless they get something better out of the new stuff.

However, in this case, it isn't.  It's not us - the guys who wrote the JWT library decided to break backwards compatibility - they did the right thing by increasing the major version (which indicates a breaking change).  Not our library so nothing we can do about it but follow along.

I'm working on a .NET Core edition of Azure Mobile Apps right now.  It still takes a dependency, but uses the 5.x edition of the Jwt library.  It's in a completely different repo and will be a completely different NuGet package.  

When we upgraded from Mobile Services to Mobile Apps, we similarly created new NuGet packages as I think major changes like that deserve such a change.  However, it does cause it's own problems - most notably, the same namespace can be incorporated for multiple different NuGets and we get confusion as to when to use one vs. the other.

So - no perfect world, I'm afraid.  You're going to have to sometimes do the compatibility leg work.

**Comment by tofutim** [comment]
Adrian, thank you for your thoughtful response.

**Comment by kjmbutu** [comment]
The Microsoft.Azure.Mobile.Server.Login NuGet package has a dependency on System.IdentityModel.Tokens.Jwt (>= 4.0.2.205111437). Should that not have been System.IdentityModel.Tokens.Jwt (>= 4.0.2.205111437 && <5.0.0)?

**Comment by adrianhall** [comment]
Yes, it should.  I'll open up a separate issue for that.

**Comment by wildough57** [comment]
It seems that the earliest available Microsoft.IdentityModel.Protocols is 2.0.0 and that has a dependency on System.IdentityModel.Tokens.Jwt (>= 5.0.0).  So, I haven't been able to find a way to revert back to Jwt 4.x at this point in time and have access to the classes in the Microsoft.IdentityModel.Protocols.WSTrust namespace.

**Comment by roxanabeloiu** [comment]
I succeeded to downgrade to System.IdentityModel.Tokens.Jwt 4.0.30826.1200, but still AppServiceLoginHandler does not exists. 
I am building the application on .NET 4.6. What are you saying is that is no way to use AppServiceLoginHandler.CreateToken without having .NET Core?

**Comment by CopyJosh** [comment]
Struggling tremendously as a new developer to Xamarin/.NET.. building a Web API in .NET Core 2.0, and came across the same instructions as the OP to incorporate Authentication..

So what am I supposed to do? I have not found any other sensible tutorial to handle custom authentication, and now the only one available has a complex set of dependencies that I am completely lost on. 

I'm using .NET Core, so the AppServiceLoginHandler.CreateToken should be available right? Except it's still getting the OP error of JWTSecurityToken claims to be defined. The Microsoft.Azure.Mobile.Server.Login package also has a warning that the package may not be compatible because it was restored using Framework 4.6 instead of .NET Core 2.0.. so what balance am I supposed to achieve here?

**Comment by rokonec** [comment]
I'd like to add that major version might indicate breaking change, but break compatibility with a platform is another level and shall be always avoided. As we won't migrate to net core, that change is for us same as if he would make package compatible with node.js only :-)
