### ISSUE TITLE
"Tell me more" link on default index.html gives a 404 page instead of docs

### ISSUE THREAD

**Issue by SmartyP** [Azure/azure-mobile-apps-net-server#188]
The default page that you get when creating an Azure Mobile App or an Azure Web App (ref: https://i.stack.imgur.com/2KoDn.jpg) links to:

http://go.microsoft.com/fwlink/?LinkID=616909&clcid=0x409

.. which then redirects to:
https://docs.microsoft.com/en-us/azure/app-service/mobile/

.. which gives a 404 page not found error.

I believe this should instead redirect to:
https://docs.microsoft.com/en-us/azure/app-service-mobile/
(notice it should be a "-" instead of a "/" as in the url the user is redirect to)

This is the default index.html that every user sees, so seems of higher priority.

**Comment by adrianhall** [comment]
Thanks - I've updated the link so it should be pointing to the right place now.
