### ISSUE TITLE
fetching service access_token

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-server#189]
There is an old example using "ServiceUser" which fetches additional user information using 
```
			//Check if the user has logged in using Facebook as Identity provider
			var fb = identities.OfType<FacebookCredentials>().FirstOrDefault();
			if (fb != null)
			{
				var accessToken = fb.AccessToken;
				result.Add("facebook", await GetProviderInfo("https://graph.facebook.com/me?access_token=" + accessToken));
			}

			//Check if the user has logged in using Microsoft Identity provider
			var ms = identities.OfType<MicrosoftAccountCredentials>().FirstOrDefault();
			if (ms != null)
			{
				var accessToken = ms.AccessToken;
				result.Add("microsoft", await GetProviderInfo("https://apis.live.net/v5.0/me/?method=GET&access_token=" + accessToken));
			}

			//Check if the user has logged in using Google as Identity provider
			var google = identities.OfType<GoogleCredentials>().FirstOrDefault();
			if (google != null)
			{
				var accessToken = google.AccessToken;
				result.Add("google", await GetProviderInfo("https://www.googleapis.com/oauth2/v1/userinfo?access_token=" + accessToken));
			}

			//Check if the user has logged in using Twitter as Identity provider
			var twitter = identities.OfType<TwitterCredentials>().FirstOrDefault();
			if (twitter != null)
			{
				var accessToken = twitter.AccessToken;
				result.Add("twitter", await GetProviderInfo("https://api.twitter.com/1.1/account/verify_credentials.json?include_email&access_token=" + accessToken));
			}
```
Now that ServiceUser is not present, how do I do the same thing? I do not see this type of identity under IPrincipal. Any help much appreciated.

**Update.** Getting some clues from https://github.com/Azure/azure-mobile-apps-net-server/blob/04d75cadc137cc478f98edfa1fa5b868e5548dfd/e2etest/Controllers/Table/AuthenticatedController.cs

I see 
```
var fbcreds = await user.GetAppServiceIdentityAsync<FacebookCredentials>(this.Request);
```
Any idea how I can get HttpRequestMessage from a signalr hub?

**Comment by adrianhall** [comment]
Azure Mobile Apps does not deal with SignalR - it's an orthogonal problem right now.  The Azure App Service (not mobile apps) controller can use GetAppServiceIdentityAsync() only if it knows the request - which would be needed to get any authentication.  If you know the context, you also know the request.

Short version - SignalR is not something we are supporting in this SDK.

**Comment by tofutim** [comment]
GetAppServiceIdentityAsync just needs the zumo token (https://github.com/Azure/azure-mobile-apps-net-server/issues/87#issuecomment-281853059), I'll work on the PR if you can review.

**Comment by adrianhall** [comment]
Yes - we will accept a PR for #87
