### ISSUE TITLE
additional auth sources?

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-server#191]
Besides Google/Msft/Facebook/Twitter/AAD, is it possible to add additional identity providers? In particular, LinkedIn or QQ? Is it possible to add it and still have Azure track this?

**Comment by pvbchak** [comment]
Thanks for the feedback. Mobile Apps uses App Service authentication, which tracks user feedback at https://feedback.azure.com/forums/169385-web-apps.
