### ISSUE TITLE
Better error messages when NotificationInstallationsController is missing required app settings

### ISSUE THREAD

**Issue by aziel** [Azure/azure-mobile-apps-net-server#192]
To reduce user unhappiness, it would be better to provide an explicit error message due to missing app settings for Push:
MS_NotificationHubName
MS_NotificationHubConnectionString.

Currently, you'll get either 500, or 404. 
Would be nice to return a 400 with "The MS_NotificationHubName app setting is null" or "The MS_NotificationHubConnectionString app settings is null" to logs or in the error response.

**Comment by adrianhall** [comment]
This would be a matter for the App Service Push feature and not a part of the server SDK.  We cannot affect the App Service Push feature.  (Not that I don't agree - it just needs to be filed elsewhere)

**Comment by aziel** [comment]
Well, not entirely.
Even if I deploy Server SDK, and the app settings are missing, you'll get bad error messages that don't tell you "the app settings I was expecting are missing".

That's why I was filing these bugs. Easy fix, but I'm not allocated to fix these.



/iPhone

**Comment by adrianhall** [comment]
... but the App Service Push overwrites the service within the server SDK (which is going away anyhow - see #180) to be replaced by a stub that doesn't do anything.
