### ISSUE TITLE
Problem getting stable_sid

### ISSUE THREAD

**Issue by chadiswar** [Azure/azure-mobile-apps-net-server#194]
I have begun upgrading my backend to the latest version.  I am one of those soles who needed the fb/google/ms provider ID in my app.  Historically, This was the code block I would use:

`
ClaimsPrincipal principal = this.User as ClaimsPrincipal;
string provider = principal.FindFirst("http://schemas.microsoft.com/identity/claims/identityprovider").Value;

ProviderCredentials creds = null;
if (string.Equals(provider, "facebook", StringComparison.OrdinalIgnoreCase))
{
    creds = await User.GetAppServiceIdentityAsync<FacebookCredentials>(this.Request);
}
else if (string.Equals(provider, "google", StringComparison.OrdinalIgnoreCase))
{
    creds = await User.GetAppServiceIdentityAsync<GoogleCredentials>(Request);
}
else if (string.Equals(provider, "microsoftaccount", StringComparison.OrdinalIgnoreCase))
{
    creds = await User.GetAppServiceIdentityAsync<MicrosoftAccountCredentials>(this.Request);
}
/// any other providers you support in your app.
string userName = creds.Claims[ClaimTypes.NameIdentifier];
string email = creds.Claims[ClaimTypes.Email];
return userName;
`
Where username was the provider ID.  This worked great and even matched up with my previous website I developed so users did not have to re-register.  

After I upgraded all of the SDK libraries, my code would not compile anymore because the ProviderCredentials object no longer contains a definition for "Claims".  So I found the article about getting the "stable_sid".  I modified my code to the following:

`                ClaimsPrincipal principal = this.User as ClaimsPrincipal;
                string provider = principal.FindFirst("http://schemas.microsoft.com/identity/claims/identityprovider").Value;

                ProviderCredentials creds = null;
                if (string.Equals(provider, "facebook", StringComparison.OrdinalIgnoreCase))
                {
                    creds = await User.GetAppServiceIdentityAsync<FacebookCredentials>(this.Request);
                }
                else if (string.Equals(provider, "google", StringComparison.OrdinalIgnoreCase))
                {
                    creds = await User.GetAppServiceIdentityAsync<GoogleCredentials>(Request);
                }
                else if (string.Equals(provider, "microsoftaccount", StringComparison.OrdinalIgnoreCase))
                {
                    creds = await User.GetAppServiceIdentityAsync<MicrosoftAccountCredentials>(this.Request);
                }
                /// any other providers you support in your app.
                /// 
                
                string userName = principal.FindFirst(ClaimTypes.NameIdentifier).Value;
                return userName;`

But what I am seeing is username returns in the old format of sid{identifier}.  Additionally when I try to get the stable sid via claimsUser.FindFirst("stable_sid"), it returns null.  When querying the version with claimsUser.FindFirst("ver") it returns the correct value of 4.  I have verified that my website has the application setting of WEBSITE_AUTH_HIDE_DEPRECATED_SID set to true - it has had this prior to my upgrade - but I am still not able to get the stable_sid.

Your help is always appreciated.

Chad

**Comment by tofutim** [comment]
This is an aside, but I never figured out where to set WEBSITE_AUTH_HIDE_DEPRECATED_SID, is that in Web.Config? Or in Azure?

**Comment by chadiswar** [comment]
More information.  I modified the portal application setting for WEBSITE_AUTH_HIDE_DEPRECATED_SID to a value of false.  This was verified as working as my claimsUser.FindFirst("ver").Value now returns "3".  I am also now able to query the claimsUser.FindFirst("stable_sid").Value but it is returning the same sid{identifier} format and not the provider ID as expected.  I am attaching a screen shot of a debug session:

![image](https://cloud.githubusercontent.com/assets/17476862/23407004/c2ff7232-fd8f-11e6-9eb9-f03affd2bb2c.png)


This is baffling to me.  Thanks for your help.

**Comment by tofutim** [comment]
Chad, instead of getting the NameIdentifier from principal (this will give you the zumo sid), you will need to look in creds.UserClaims. There is no FindFirst function, but you can doctor your own using Linq. Here is what I am using:

```
ProviderCredentials creds = null;

				// for zumo the creds will be provided
				switch (providerClaim.Value)
				{
					case "google":
						creds = await user.GetAppServiceIdentityAsync<GoogleCredentials>(request);
						break;
					case "facebook":
						creds = await user.GetAppServiceIdentityAsync<FacebookCredentials>(request);
						break;
					case "twitter":
						creds = await user.GetAppServiceIdentityAsync<TwitterCredentials>(request);
						break;
					case "microsoft":
						creds = await user.GetAppServiceIdentityAsync<MicrosoftAccountCredentials>(request);
						break;
					case "aad":
						creds = await user.GetAppServiceIdentityAsync<AzureActiveDirectoryCredentials>(request);
						break;
				}

				if (creds != null)
				{
					// fetch the nameidentifier will hold the id we want
					Claim idClaim = creds.UserClaims.FirstOrDefault(c => c.Type == AadClaimTypes.Identifier);
					if (idClaim != null)
					{
						var proposedSid = $"{providerClaim.Value}|{idClaim.Value}";						
						return proposedSid;
					}
					else
					{
						// return the zumo sid
						var zumoSid = $"{"zumo"}|{user.GetZumoSid()}";		// stable_sid
						return zumoSid;
					}
				}
			}
```

**Comment by chadiswar** [comment]
This works really well thank you.  I think my confusion came from the documentation in that I was expecting principal.FindFirst(ClaimTypes.NameIdentifier).Value to return just the Provider ID but in fact, it is returning a hashed value based on the provider id?

As for the WEBSITE_AUTH_HIDE_DEPRECATED_SID.  I have set that as an application setting in the Azure portal with a value of "true" or "false" without the quotes.  However, I think I remember reading that App Services set up after a certain point do not need this value and thus, will note generate a claimsUser.FindFirst("stable_sid").  You can check it by querying the claimsUser.FindFirst("ver").  A return of 3 means that the ClaimTypes.NamedIdentifier is based on the provider email and 4 means it is based on the Provider ID.

Could a mod please clarify any of this information if I am in error?

Cheers and thank you for you help.

Chad

**Comment by elamalani** [comment]
Closing this issue since the question is answered.
