### ISSUE TITLE
Local Debugging - 401 Unauthorized

### ISSUE THREAD

**Issue by winnicki** [Azure/azure-mobile-apps-net-server#197]
I cloned the [Complete TodoList .NET Backend](https://github.com/Azure-Samples/app-service-mobile-dotnet-backend-quickstart) and followed the steps from [Local development and debugging the Mobile App .NET server backend](https://github.com/Azure/azure-mobile-apps-net-server/wiki/Local-development-and-debugging-the-Mobile-App-.NET-server-backend). I can run the [Complete TodoList Android app](https://github.com/Azure-Samples/app-service-mobile-xamarin-android-quickstart) which I've updated as well for local API debugging and I can debug locally with breakpoints and everything works fine _as long as I remove [Authorize] from the TodoItemController._ 

After logging in through Facebook and inspecting the MobileClient I can see my sid and token, but if I attempt to POST or GET from TodoItemController I immediately get a 401 and the API doesn't throw any exception for me to further investigate why this is happening. 

I have the correct SigningKey, ValidAudience, and ValidIssuer values in my config and even with the trailing '/' on the endpoints. 

Can someone try to reproduce this issue? I've branched both the Android and .NET backend complete repo's and I can publish them to you if that helps.

I've also read through the authorization and authentication sections of Adrian Hall's GitHub book but I wasn't able to resolve the issue. I tried putting the configs in the Web.Debug.config as well as Web.config.

Notes: 
I updated the NuGet packages to latest after cloning the completed samples.. I wonder if this is the issue.

Repro Steps:
1. Clone the complete backend and Android app
2. Update all NuGet packages in both client and server solutions
3. Configure both solutions for local debugging
4. Run the backend locally using Google Chrome
5. Sign in through Facebook through the Android app. You should get the successful sign in dialog with the sid
6. Add a todo item. You should receive a 401 Unauthorized at this point.

**Comment by winnicki** [comment]
I realized that the issue was probably from updating the NuGet packages.. so I started from the clean master commit from the backend .NET sample and was able to get local debugging working _with_ the [Authorize] attribute after signing into Facebook.

I'm going to branch this off and then test updating certain packages. Hopefully I should be able to at least update the Azure.Mobile.Server packages without any issues but I'll post my results here.

**Comment by adrianhall** [comment]
Update and reopen if you bump into issues.  However, to keep the issues related to just things that need dev, I'm going to close this.

**Comment by mrsmitty** [comment]
Check your version of System.IdentityModel.Tokens.Jwt, preferably use 4.0.40306.1554.

I was on 5.1.3 and was experiencing the same issue receiving:
Exception thrown: 'System.TypeLoadException' in Microsoft.Azure.Mobile.Server.Authentication.dll

I proxied the GetAppServiceTokenHandler() in my own IAppServiceTokenHandler and found it was failing in TryValidateLoginToken() with the following:
Could not load type 'System.IdentityModel.Tokens.JwtSecurityToken' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.3.0

Downgraded and it resolved the issue.

**Comment by winnicki** [comment]
@mrsmitty Thanks, that's helpful. I did downgrade and then only updated the Azure packages and it's working now.

**Comment by pavinan** [comment]
@mrsmitty Thanks. Additionally, I have to change the versions of both binding redirects in web.config for that library to 4.0.40306.1554. For some reason nuget didn't change there.
