### ISSUE TITLE
Use App Service Push instead

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-server#198]
What does this mean?

![instead](https://cloud.githubusercontent.com/assets/157766/23493496/12997ffe-fec1-11e6-9301-bb46f4a06753.png)

I tried looking for an "AppServicePush" command in config, but nothing.

**Comment by angusbreno** [comment]
App Service Push is a feature provided by Azure Portal, **not by the package anymore**.
This is what u are looking for: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-push

**Comment by oatsoda** [comment]
When you say

> The App Service Push configuration is a feature provided by Azure Portal, not by the package anymore.

Do you mean that physically the /push/installation endpoint is provided by something else?  Or just that the `NotificationsExtensionConfigProvider.Initialize` is executed somehow by updating the Azure portal?

I am just struggling to understand how the /push/installations endpoint works when you have update the Push section in the portal, but if you don't then this endpoint is not available...

**Comment by tecsined** [comment]
The documentation: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-backend-how-to-use-server-sdk#create-app

Is outdated and is showing  that it requires AddPushNotifications but when you try it an obsolete message appears. Where is the correct document to understand push notifications configuration for back-end service

**Comment by bolicd** [comment]
Have the same problem. Where is update documentation on this one? All i get in searches is obsolete documentation, making it really hard to implement properly ...

**Comment by mahendranv** [comment]
I was on 4.0.2 of Azure.Mobile sdk then recently migrated to 4.1.1.

On both I am facing the following issue

> "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

can anyone confirm we're still using the same application URL format?

`public static string ApplicationURL = @"https://xxxx.azurewebsites.net";`

**Comment by angusbreno** [comment]
Guys, push notification is not provided by the nuget library anymore, it's obsolete. You can find some tutorials using app service but i don't recomend either.

My advice as a Microsoft cloud architect:
Don't use push from easy way (app service push) cause it's not fully customizable. 
Use notifications hub in azure and create some copy-paste code from the old push library: https://github.com/Azure/azure-mobile-apps-net-server/tree/master/src/Microsoft.Azure.Mobile.Server.Notifications
You will be more successful doing this.

I have plans to create some kind of cloud library helpers with push too, but i have real life too.

**Comment by mahendranv** [comment]
> @mahendranv, yes, still the same `https://{myapp}.azurewebsites.net` application URL, nothing changed to the URL.
> 
> "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable" suggests it might be a temporary issue with the backend. Try restarting and redeploying your app. If the issue persists, please open a support ticket with Azure Support from Azure portal.

Thanks. Just wanted to confirm the endpoint is still the same. We've also tried to restart the app service and changing notification hub back and forth with no luck. Will report this to support team.
