### ISSUE TITLE
Interface ITableData should not be dependent on ASP.net

### ISSUE THREAD

**Issue by DibranMulder** [Azure/azure-mobile-apps-net-server#199]
Offline Sync entities have to implement the ITableData originating from the Microsoft.Azure.Mobile.Server.Tables NuGet package. However this package depends on:

> Dependencies
> Microsoft.Azure.Mobile.Server (>= 1.1.157.1) 
> Microsoft.AspNet.WebApi.Client (>= 5.2.3) 
> Microsoft.AspNet.WebApi.Core (>= 5.2.3) 
> Microsoft.AspNet.WebApi.OData (>= 5.5.1) 
> Microsoft.Data.Edm (>= 5.6.4) 
> Microsoft.Data.OData (>= 5.6.4) 
> Newtonsoft.Json (>= 6.0.8) 
> System.Spatial (>= 5.6.4) 

And this results in that the entities can't be shared between Xamarin and ASP.net projects and therefore can't be located in shared Portable Class libraries, which sadly enforces me to duplicate my entities.

**Comment by adrianhall** [comment]
You cannot share the ITableData interface between client and server.  Your client package needs to be independent.
