### ISSUE TITLE
How can I create a spatial index if PK isn't a clustered index?

### ISSUE THREAD

**Issue by julianonunes** [Azure/azure-mobile-apps-net-server#202]
I just saw the page https://github.com/Azure/azure-mobile-apps-net-server/wiki/Why-does-CreatedAt-have-a-Clustered-Index saying that I can't make Id a clustered index, however I'm adding geography column to my database and need to create a spatial index for better performance. The problem is that the SDK automatically sets CreatedAt as the clustered index and not the Primary Key.

Do I have any other option?

**Comment by adrianhall** [comment]
Azure Mobile Apps does not support Spatial queries right now, and we are unlikely to add it any time soon.
