### ISSUE TITLE
ApiController call causes SignalR to fail

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-server#206]
with a WebSocketException. One must restart the web app for SignalR to work again. If anyone has any insight it would be much appreciated. 

My notes here: http://stackoverflow.com/questions/42916053/zumo-invokeapiasync-causes-signalr-to-stop-working

**Comment by adrianhall** [comment]
From the notes, this is dealing with App Service Authentication, not Mobile Apps.  As a result of that analysis - closing.
