### ISSUE TITLE
Does Azure mobile service supports Asp.Net Core applications?

### ISSUE THREAD

**Issue by gayan1991** [Azure/azure-mobile-apps-net-server#214]
I have MVC 5 web api application that uses azure mobile services. From there I uses sync services and **Tablecontroller** <TData> for synchronisation with the mobile. I want to know that **tablecontroller** is available for .**net core/ ASP.net core**. If there is, is there any samples? If not, what other ways we could build the azure mobile service in **Asp.Net Core project**?

**Comment by adrianhall** [comment]
You cannot use Azure Mobile Apps with ASP.NET Core - see #214.

**Comment by gayan1991** [comment]
@adrianhall If you do not mind, could you answer following.
If i want to build azure sync service, which procedure I should use? Normal ApiController/ ODataController/ Any other choice?
If I want use TableController which project should I choose?

**Comment by adrianhall** [comment]
TableControllers require an ASP.NET (non-Core) project and the Azure Mobile Apps.

There are lots of other options.  If, however, you want to use Azure Mobile Apps, then you must create the project in a particular way.

**Comment by IeuanWalker** [comment]
@adrianhall Why can't you publish a .net core application to azure app services? And is this going to change in the future?

**Comment by samrgc** [comment]
Sorry. We are now in 2019. What is the progress? Is there offline synchronization available for asp.net core web api that can be used to substitute for Azure Mobile Apps' offline data sync?

**Comment by russelarms** [comment]
Hi, @samrgc!
Unfortunately, we are not investing in any feature work for now:
https://github.com/Azure/azure-mobile-apps-net-server#future-of-azure-mobile-apps

**Comment by adrianhall** [comment]
Hi everyone - in case you get here from Google search, we do now support ASP.NET Core - check out https://azure.github.io/azure-mobile-apps and install v5.0.0 of the Microsoft.AspNetCore.Datasync libraries.  They are completely different, but then again, so is ASP.NET Core.
