### ISSUE TITLE
Bad Request using Client-managed authentication with Google

### ISSUE THREAD

**Issue by JeffDalby** [Azure/azure-mobile-apps-net-server#217]
According to the docs found here: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#client-facebook
Client side authentication should simple be:
var token = new JObject();
// Replace access_token_value with actual value of your access token obtained
// using the Facebook or Google SDK.
token.Add("access_token", "access_token_value");

user = await client.LoginAsync(MobileServiceAuthenticationProvider.Facebook, token);

However when attempting to login via Google (changing the provider in the above example to Google) using this method we simply get a "Bad Request" response.  Using server managed auth works fine with the same backend, but due to the recent google changes we'll have to go away from it.  We are now implementing Xamarin Auth, and are able to get the token on the client end, but it appears that more is needed to authenticate to Google.  I suspect there should be more in the token, but I've not yet found a combination that works.  Is there any proper documentation for this?  Does it actually work?  If so what should be contained in the Token?

Along those lines when setting up authentication on the backend with Google we have to create a web api authentication endpoint, however on the client side we have to create an app endpoint.  Can that even work, given that both endpoints are created for the same account?  Does the Mobile App backend use the info from the Authentication section in the Azure portal when using Client managed authentication?

**Comment by JeffDalby** [comment]
OK turns out you also need to add an id_token with it's corresponding value to the token JObject.  Documentation should probably be updated.

**Comment by mpnow** [comment]
@JeffDalby  How did you retrieve the id_token from the Xamarin.Auth call on your client? When I use Xamarin.Auth on my iOS client, Account.Properties does not contain id_token. So I read that in order to get id_token, you have to supply a client_secret; but when I add that to my OAuth2Authenticator object (even though you're not supposed to use client_secret on a mobile client), then the Xamarin.Auth call never calls OnAuthCompleted.

**Comment by mpnow** [comment]
@JeffDalby OK I see if I include a scope of "https://www.googleapis.com/auth/userinfo.email" in my Xamarin.Auth client function, it returns me an id_token.  But when I include this id_token value in building my server-side UserCredential object and then try to read some Google Drive files, I don't get any errors but it returns me no files.  When I use an access token and refresh token that were created by a web authentication, I do get my expected files returned.  So it seems I'm still missing something.  What code are you using server-side to login using your client-obtained credentials?

**Comment by JeffDalby** [comment]
So above I was referring to the Azure mobile stuff not Xamarin Auth.  Since the fix came out for Azure right now I'm using it on UWP, but still using Xamarin auth on iOS, so I guess you could say I've got it working both ways. 

For xamarin Auth my end point is the generic/web type not a specific iOS one, which is what allowed me to do the "Bad" thing of using the client secret on the client side...but sometimes you just have to get things working or you loose customers, sucky trade off, but it is what it is.  We primarily had to do that because we have an existing Azure Mobile App so we needed to be able to reuse it.

Anyway the iOS Xamarin auth code looks like this:
uthenticationState.Authenticator = new OAuth2Authenticator
            (
                clientId: "*********.apps.googleusercontent.com",
                clientSecret: "********",
                authorizeUrl: new Uri("https://accounts.google.com/o/oauth2/auth"),
                accessTokenUrl: new Uri("https://www.googleapis.com/oauth2/v4/token"),
                redirectUrl: new Uri("com.googleusercontent.apps.********:/oauth2redirect"),
                scope: "https://www.googleapis.com/auth/userinfo.email
https://www.googleapis.com/auth/userinfo.profile",
                getUsernameAsync: null,
                isUsingNativeUI: true
                );
then in Auth completed we grab the token like this:

AuthenticationState.Authenticator.Completed +=
                async (s, ea) =>
                {
                    var token = new JObject();
                    token.Add("access_token", ea.Account.Properties["access_token"]);
                    token.Add("id_token", ea.Account.Properties["id_token"]);
                MobileServiceUser = await _MobileServiceClient.MobileService.LoginAsync(myidp, token);
                        SaveCredentials(MobileServiceUser.UserId, MobileServiceUser.MobileServiceAuthenticationToken);
                        LoggedIn = true;
}

Now in reality a lot of that is wrapped in try catches but I put it like that to be a little more readable.  In our case we aren't going back to Google (you can see us going back to the Mobile service above), so I've not tried to pass those credentials back to grab some files.  I would think it is critical to make sure you have the proper things in the scope so you have rights to access google drive, couldn't tell if you have that or not.

Also not using the latest v4 or whatever it breaks all that because it switches the login async function to do server side auth vs client side. We are using that way of doing thing on UWP...At some point soon I'll have to decide which to go with and standardize, but at the time all of our iOS clients couldn't log in to Google, and UWP support wasn't finished in Xamarin Auth, so well we made a mess, but at least our customers can log in.

If you haven't checked it out there's a super helpful slack channel for Xamarin Auth, links to it are on the Xamarin Auth main page.

**Comment by mpnow** [comment]
@JeffDalby Thanks for the info.  When I use my web Client Id and Client Secret in my OAuth2Authenticator constructor, I get "Invalid request - custom scheme URIs are not allowed for 'WEB' client type".  So not sure how you got around that issue...?

Thanks, will check out the Slack channel now for sure.

**Comment by mpnow** [comment]
OK I finally got it working to authenticate on the iOS client and access Google Drive on a server-side process.  Ultimately I think it was a combination of:

- Using a scope of https://www.googleapis.com/auth/drive, not https://www.googleapis.com/auth/drive.file

- Using the Developer Console's **iOS Client Id** (and thus a null Client Secret) in both the iOS client and the server login.  I'm not using a **Web** Client Id at all now.

- Probably the most significant: I was previously passing only the access_token and refresh_token from my iOS authentication to the server, and for the server login, was then building the TokenResponse property of the UserCredential object with only those two properties. Instead I now pass the entire Account object from iOS client to the server, and then for the server login, populate all of the other properties from Account in constructing the UserCredential object:

`            var credential = new UserCredential(flow, userId, new TokenResponse
            {
                AccessToken = account.Properties["access_token"],
                ExpiresInSeconds = Convert.ToInt64(account.Properties["expires_in"]),
                RefreshToken = account.Properties["refresh_token"],
                Scope = "https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/userinfo.email",
                TokenType = account.Properties["token_type"]
            });
`

(Note that I didn't need to set IdToken to get it to work.)
