### ISSUE TITLE
Json.net Re‌​ferenceLoopHandling setting seems to be ignored

### ISSUE THREAD

**Issue by julianonunes** [Azure/azure-mobile-apps-net-server#218]
Even though I'm setting `SerializerSettings.Re‌​ferenceLoopHandling` in my Startup class, I'm still getting circular references exceptions in my controllers.

Here's my startup class:

```
public partial class Startup
    {
        public static void ConfigureMobileApp(IAppBuilder app)
        {

            HttpConfiguration config = new HttpConfiguration();

            new MobileAppConfiguration()
                .UseDefaultConfiguration()
                .ApplyTo(config);

            config.MapHttpAttributeRoutes();

            // Use Entity Framework Code First to create database tables based on your DbContext
            Database.SetInitializer(new MobileServiceInitializer());
            MobileAppSettingsDictionary settings = config.GetMobileAppSettingsProvider().GetMobileAppSettings();

            config.Formatters.JsonFormatter.SerializerSettings.Re‌​ferenceLoopHandling = ReferenceLoopHandling.Ignore;

            config.Services.Add(typeof(IExceptionLogger), new AiExceptionLogger());

            if (string.IsNullOrEmpty(settings.HostName))
            {
                app.UseAppServiceAuthentication(new AppServiceAuthenticationOptions
                {
                    // This middleware is intended to be used locally for debugging. By default, HostName will
                    // only have a value when running in an App Service application.
                    SigningKey = ConfigurationManager.AppSettings["SigningKey"],
                    ValidAudiences = new[] { ConfigurationManager.AppSettings["ValidAudience"] },
                    ValidIssuers = new[] { ConfigurationManager.AppSettings["ValidIssuer"] },
                    TokenHandler = config.GetAppServiceTokenHandler()
                });
            }

            app.UseWebApi(config);
        }
    }
```

Am I missing something?

BTW I also posted this question on [StackOverflow](http://stackoverflow.com/questions/43882563/referenceloophandling-ignore-not-working-for-azure-mobile-app-service-to-ignore).

**Comment by oatsoda** [comment]
The settings that you apply at a global level do not get applied to the TableControllers.

See [how to configure the Table Controllers documentation](https://github.com/Azure/azure-mobile-apps-net-server/wiki/Configuring-MobileAppController-and-TableController-Settings).

For example:

    new MobileAppConfiguration()
    	.UseDefaultConfiguration()
    	.WithTableControllerConfigProvider(new MyTableControllerConfigProvider())
    	.ApplyTo(config);
    
    public class MyTableControllerConfigProvider : TableControllerConfigProvider
    {
    	public override void Configure(HttpControllerSettings controllerSettings, HttpControllerDescriptor controllerDescriptor)
    	{
    		base.Configure(controllerSettings, controllerDescriptor);
    
    		controllerSettings.Formatters.JsonFormatter.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.None;
    		controllerSettings.Formatters.JsonFormatter.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
    	}
    }

**Comment by elamalani** [comment]
@julianonunes Thanks for using Azure Mobile Apps. There were some suggestions on StackOverflow on how to fix those issues. Did you get a chance to look at it?

I'll close this issue for now since its a year old. Feel free to contact us in case you have any question.

**Comment by julianonunes** [comment]
I don't remember how the problem was solved, but thank you anyway.
