### ISSUE TITLE
Provide way to log DbExceptions occured in TableController

### ISSUE THREAD

**Issue by jiberan** [Azure/azure-mobile-apps-net-server#220]
In **SubmitChangesAsync** in class **EntityUtils** [https://github.com/Azure/azure-mobile-apps-net-server/blob/master/src/Microsoft.Azure.Mobile.Server.Entity/Tables/EntityUtils.cs#L62](https://github.com/Azure/azure-mobile-apps-net-server/blob/master/src/Microsoft.Azure.Mobile.Server.Entity/Tables/EntityUtils.cs#L62) you are catching DbExceptions and then throwing HttpResponseException.

This will cause, that there is no way to catch those original exceptions and log then( to app insights, etc.)

What would be correct way to catch those exceptions?

Thanks,
Jiri

**Comment by ericbrunner** [comment]
Hi Jiri, First I am only a consumet for that SDK but maybe I can help you. Today I got some similar exceptions in my mobile app TableController when saving changes. In my Xamarin.Forms App I could catch those HttpResposeException indirectly via MobileServicePushFailedException . Then extracted the errors and tried to solve the issue.
See conflict handling: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter3/client/#handling-conflict-resolution

In case of a HttpResponseException the error.Result is not your server database record. It contains a JSON object with one property called message. The content e.g. could contain the underlying database error. In my case there was a message like "Transaction deadlocked ...."

You can check if you get that exception via error.Error property on the MobileServiceTableOperationError instance.

In my case I check that, log a message in Application Insight and return (keep the pending changes). In a next sync run sometimes later on the client the update push operation will be re tried again until it goes through.

Hope it help. I can send you a link to full working code sample on gist.

Eric

**Comment by elamalani** [comment]
@jiberan Thanks for using Azure Mobile Ap ps. It looks like a year old issue and I'll close it for now. Please follow the suggestion shared by ericbrunner. Thanks!
