### ISSUE TITLE
Add overload to GetAppServiceIdentityAsync for passing token instead of HttpRequestMessage

### ISSUE THREAD

**Issue by filoe** [Azure/azure-mobile-apps-net-server#225]
According to this test: https://github.com/Azure/azure-mobile-apps-net-server/blob/master/test/Microsoft.Azure.Mobile.Server.Authentication.Test/IPrincipalExtensionsTests.cs#L244 the parameter needed for inside of the GetAppServiceIdentityAsync method is the token.
Why do we have to pass the whole HttpRequestMessage to the method. In some scenarios it is not possible to retrieve the HttpRequestMessage object and it is everything else than intuitive to create a new HttpRequestMessage and add a single field to the header.

Feature request: Add more overloads to the GetAppServiceIdentityAsync method.

**Comment by elamalani** [comment]
@filoe Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). We won't be adding new features in the product. 

I'll close this issue for now but let us know if you have any questions. Thanks!
