### ISSUE TITLE
Weird behavior when calling the "get all" method of a controller

### ISSUE THREAD

**Issue by thombrink** [Azure/azure-mobile-apps-net-server#230]
When I have te following code
public IQueryable<Reservation> GetAllReservation()

I will get less results then when I change it to
public IQueryable<Reservation> GetAllReservation(ODataQueryOptions query)

Without changing any other code!

Is this expected behavior? I can't seem to find anything about it in the documentation.

**Comment by elamalani** [comment]
@thombrink Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). I'll close this issue for now but let us know if you have any questions. Thanks!
