### ISSUE TITLE
aad logout leads to blank me

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-server#237]
For some reason, this took me a long time to debug.

If you have an app with a valid token (from Azure Active Directory) and then elsewhere, on a different machine even, you login and logout of Azure Active Directory, the .auth/me?provider=aad will give you the empty set {} when queried. If you login again (on a yet a different machine) suddenly the token will work again.

**Comment by elamalani** [comment]
@tofutim Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). 

I'll close this issue for now but let us know if you have any questions. Thanks!
