### ISSUE TITLE
Using Guid instead of stringified Guid

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-server#238]
I noticed that the index for tables is a stringified Guid. Is there a reason why the database doesn't just directly store a Guid for Id?

**Comment by codegrue** [comment]
Adrian Hall replied in another thread that they didn't want to force it to be only GUIDs. You can use any natural key that can be stringified.

**Comment by tofutim** [comment]
I suppose I can accept that... although Adrian doesn't seem to be around...
