### ISSUE TITLE
Changing db schema

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-server#239]
Is there a way to use an alternative db schema. Rather than using 'dbo', I want to use something else.

**Comment by tofutim** [comment]
amazingly, this was all it took

[Table("TodoItems", Schema ="usr")]

**Comment by tofutim** [comment]
I spoke too soon, this work with creating and inserting, but when sync, dbo is called again... weird.

**Comment by elamalani** [comment]
@tofutim This documentation might be helpful to you - https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter3/server/#changing-the-mobile-schema

I will close the issue for now but feel free to contact us if you have questions.
