### ISSUE TITLE
AppServiceLoginHandler.CreateToken()

### ISSUE THREAD

**Issue by mpoirier101** [Azure/azure-mobile-apps-net-server#240]
Where is the documentation for AppServiceLoginHandler.CreateToken() ?

In object browser all I see is:

public static System.IdentityModel.Tokens.JwtSecurityToken CreateToken(System.Collections.Generic.IEnumerable<System.Security.Claims.Claim> claims, string secretKey, string audience, string issuer, System.TimeSpan? lifetime)

Thanks !

**Comment by elamalani** [comment]
@asierpn Thanks for using Azure Mobile Apps. Did you find the documentation for that method? I'm not sure if we have publicly documented it.

I'll close this issue for now but let us know if you have any questions. Thanks!
