### ISSUE TITLE
Data Sync features has stoped working from mobile app to server in cordova

### ISSUE THREAD

**Issue by ManiSubbu** [Azure/azure-mobile-apps-net-server#244]
Push functionality has been working as intended till April 10, 2018; However after that we have observed the following error while accessing the push functionality.

PATCH https://*********/tables/Student/*************** 500 (Internal Server Error)
Sync error! Invalid column name *****. 

As the temporary solution we have removed that particular column in store setup. Now sync feature has working as before. Why it has worked before and facing issue Now?

Please let us know If any of the latest Azure releases has caused that issue?

**Comment by MatkovIvan** [comment]
Hi @ManiSubbu 

Thanks for getting in touch.
Could you please provide us the full backend log with stack trace and problem column name?
Did you update anything in your application on that date?
This info will help us to understand what's going on and will allow solve your problem.

Best,
Ivan

**Comment by elamalani** [comment]
Closing this issue as we havent heard back.
