### ISSUE TITLE
Is the table controller supported?

### ISSUE THREAD

**Issue by gayan1991** [Azure/azure-mobile-apps-net-server#246]
In previoud .net core environments, azure mobile sync services were not supported and because of that table controllers were replaced by api controllers?

With the .net core 3.0 coming up, are table controller sync services supported with the new .net core standard?

**Comment by dhei** [comment]
Hi @gayan1991,

Thanks for getting in touch.

I am not sure if I understand what is "azure mobile sync services". Do you mean offline sync feature of Azure Mobile Apps? We only support .NET Framework at this moment, and currently have no plan to support .NET Core in Azure Mobile Apps server SDK.

**Comment by gayan1991** [comment]
Hi sorry forgive me for my words I accidentally typed the wrong title. Anyway, are you guys planning to move the technology to .Net core.

**Comment by dhei** [comment]
@gayan1991, thanks for using Azure Mobile Apps.

At this point, we don't have plans to support .NET Core in the near future. Please read the [Readme section](https://github.com/Azure/azure-mobile-apps-net-server#future-of-azure-mobile-apps) on this repo which talks about the future of Azure Mobile Apps.
