### ISSUE TITLE
Unsecure JQuery and JQuery-UI Version

### ISSUE THREAD

**Issue by RaoulHolzer** [Azure/azure-mobile-apps-net-server#248]
In the current release the Jquery and Jquery-UI are out of date.

We had a security audit, which the auditor  Reports this as an Issue.

I'have made fowwling Pull Request #245 as solution.

**Comment by jwallra** [comment]
Thanks for the heads up, @RaoulHolzer.  I've accepted the PR and we're looking into updating the code deployed by default in our quickstarts with your changes.
