### ISSUE TITLE
Odata Query() vs QueryAsync()

### ISSUE THREAD

**Issue by josuuribe** [Azure/azure-mobile-apps-net-server#251]
Hi,

I am using a mobile application and I need to filter pull using an Id this id does not belong to object so i can not use it directly, DomainManager.Query() method does not accept parameters, so I have tried to use QueryAsync() method that accepts other parameters apart from OData parameters

The problem is I have a GET like:

_https://subdomain.azurewebsites.net/tables/acmes?$filter=(updatedAt%20ge%20datetimeoffset'2018-09-30T17%3A53%3A05.6680000%2B00%3A00')&$orderby=updatedAt&$skip=0&$top=50&id=9c70ad2c-b159-4946-b9f6-ac6e494afc5d&__includeDeleted=true_

I have a controller with:

>         [Route("")]
>         [HttpGet]
>         public IQueryable<AcmeDto> GetAllAcme(ODataQueryOptions query, string id)
>         {
>             return domain.QueryAsync(query,id);
>         }
> 
>         [Route("")]
>         [HttpGet]
>         public IQueryable<AcmeDto> GetAllAcme()
>         {
>             return Query();
>         }

When Query() is executed the value for **this.Request.RequestUri** is: 

https: //demo.azurewebsites.net/tables/acmes?$filter=(**UpdatedAt** ge datetimeoffset'2018-09-27T16:20:27.5970000%2B00:00')&$orderby=**UpdatedAt**&$skip=0&$top=50&__includeDeleted=false HTTP/1.1&**$select=Name,MimeType,Url,UserId,BlobGuid,DevicesId,Data,Id,Version,CreatedAt,UpdatedAt,Deleted**

But when QueryAsync() is executed the value for **this.Request.RequestUri** is: 

https: //demo.azurewebsites.net/tables/acmes?$filter=(**updatedAt** ge datetimeoffset'2018-09-30T17:53:05.6680000%2B00:00')&$orderby=**updatedAt**&$skip=0&$top=50&id=9c70ad2c-b159-4946-b9f6-ac6e494afc5d&__includeDeleted=true

One of the problems is I have an error like:
**Microsoft.Data.OData.ODataException: 'Could not find a property named 'updatedAt' on type 'AcmeDto'.'**

I suppose for Query() there is somekind of url preprocesssing or entity matching or any else, How can be it replicated in QueryAsync()?

**Comment by achocron** [comment]
Hey- I have a few questions to help understand the problem you are having. 

1. What exactly is happening when you call `Query()`? Is that a wrapper method that you added to your controller? Or is it part of something you've imported that we aren't seeing? (In other words, what is the full qualification of that method?) - Alternatively, a call stack at the two query calls could prove helpful.

2. What storage is your mobile backend using? Azure Table Storage or SQL Database?

3. Is your schema case-sensitive? It appears that there is a capitalization difference between the `updatedAt` filters in the two URLs.

Thanks!

**Comment by clpolet** [comment]
We haven't heard from you for a while so I'll go ahead and close this issue. Feel free to comment and we'll reopen.

**Comment by josuuribe** [comment]
Thanks for the questión seems the problem was solved using [EnableQuery] attribute on controller.

**Comment by zadeabhi** [comment]
We are facing similar issue with our application , below is the stack trace
{
    "message": "The query specified in the URI is not valid. Could not find a property named 'updatedAt' on type 'WebApplication1.DataObjects.TodoItem'.",
    "exceptionMessage": "Could not find a property named 'updatedAt' on type 'WebApplication1.DataObjects.TodoItem'.",
    "exceptionType": "Microsoft.Data.OData.ODataException",
    "stackTrace": "   at Microsoft.Data.OData.Query.EndPathBinder.GeneratePropertyAccessQueryForOpenType(EndPathToken endPathToken, SingleValueNode parentNode)\r\n   at Microsoft.Data.OData.Query.EndPathBinder.BindEndPath(EndPathToken endPathToken, BindingState state)\r\n   at Microsoft.Data.OData.Query.MetadataBinder.BindEndPath(EndPathToken endPathToken)\r\n   at Microsoft.Data.OData.Query.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.Data.OData.Query.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)\r\n   at Microsoft.Data.OData.Query.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.Data.OData.Query.MetadataBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.Data.OData.Query.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.Data.OData.Query.FilterBinder.BindFilter(QueryToken filter)\r\n   at Microsoft.Data.OData.Query.ODataUriParser.ParseFilterImplementation(String filter, IEdmType elementType, IEdmEntitySet entitySet)\r\n   at System.Web.Http.OData.Query.FilterQueryOption.get_FilterClause()\r\n   at System.Web.Http.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)\r\n   at System.Web.Http.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.Http.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at System.Web.Http.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.Http.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)\r\n   at System.Web.Http.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)\r\n   at System.Web.Http.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"
}
