### ISSUE TITLE
MobileServiceClient.GetPush().RegisterAsync is throwing HTTP 400 sometimes since last friday

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps-net-server#254]
It has been working fine the last weeks, but since last friday (11/02) I've started to see this issue in Application Insights and AppCenter. 

It's happening to UWP and Xamarin Android clients, and not all requests are affected, less than the 5% of requests are affected by this issue.

**Comment by dhei** [comment]
Hi @asierpn,

This sounds like an intermittent issue. Is it still happening today?

**Comment by asierpn** [comment]
Hi @dhei,

Yes, it is still happening today

![appinsights](https://user-images.githubusercontent.com/9281751/48057927-874b7680-e1b5-11e8-82c6-43b641aa5ca1.png)

**Comment by asierpn** [comment]
I've had more than 24 hours without seeing the issue, I think it's resolved.

Thanks.
