### ISSUE TITLE
Specify Table name

### ISSUE THREAD

**Issue by kellyelton** [Azure/azure-mobile-apps-net-server#270]
How do I specify the Table name used by the `TableController`?

**Comment by dhei** [comment]
You may follow [How to: Define a table controller](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-backend-how-to-use-server-sdk#define-table-controller) documentation:

>Define a Table Controller to expose a SQL table to mobile clients. Configuring a Table Controller requires three steps:
Create a Data Transfer Object (DTO) class.
Configure a table reference in the Mobile DbContext class.
Create a table controller.

**Comment by kellyelton** [comment]
Yes

**Comment by dhei** [comment]
@kellyelton Please take a look at [Changing the Mobile Schema](https://adrianhall.gitlab.io/develop-mobile-apps-with-csharp-and-azure/chapter3/server/#changing-the-mobile-schema) section of the zumo book. 


> Entity Framework adds an s onto the end of the model to create the table name. If you have a model named TodoItem, the table is called TodoItems in the database. You can use this same annotation to adjust the table name if it is not to your liking.


To be honest I am not expert on Entity Framework, but it seems possible to do by defining your own schema.
