### ISSUE TITLE
Error authenticating with Google Account

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps-net-server#280]
The /.auth/login/Google endpoint is raising a 401 error when doing client flow authentication since last friday 2019-06-14 at 21:00 UTC +02:00. We are using this code to login with client flow:

```
            var zumoPayload = new JObject()
            {
              ["id_token"] = _id_token,
              ["access_token"] = _access_token
            };
            user = await _mobileService.LoginAsync(MobileServiceAuthenticationProvider.Google, zumoPayload);
```

The claims returned by GetAppServiceIdentityAsync have changed also at the same time, we receive the claim "email" instead of "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" and "sub" instead of "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier".

Our Android users cannot login since las friday because we use client flow from Android, server flow is working fine.

Please fix this!!

**Comment by dhei** [comment]
Hi @asierpn,

Sorry to hear that you ran into this issue.

We are investigating this and trying to reproduce the 401 issue you encountered with Google client flow. 

In the meanwhile, please [enable Diagnostic logs for App Service](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#enablediag) and share the diagnostic logs of the login stack trace with us.

Thank you.

**Comment by asierpn** [comment]
Hi @dhei,

Thanks for your quick answer.

The issue is the same reported [here](https://social.msdn.microsoft.com/Forums/en-US/48feecef-2d67-4d9b-8143-64d265868f25/web-app-authentication-issue-jwt-validation-failed-idx10501-signature-validation-failed-unable?forum=windowsazurewebsitespreview), and fortunately a Microsoft engineer has applied a temporary patch to our production app service and is working fine now.

Best Regards,
Asier

**Comment by guperrot** [comment]
Glad the fix worked for you and that explains why we could not reproduce yesterday.
