### ISSUE TITLE
MobileServiceClient.GetPush().RegisterAsync throws HTTP 400 when called from iOS 13

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps-net-server#283]
The MobileServiceClient.GetPush().RegisterAsync method is failing when called from iOS 13 with the last version of Xamarin IOS.

I can see the HTTP 400 error in the AI log for the call to the /push/installations/ endpoint.

![image](https://user-images.githubusercontent.com/9281751/66326839-013a3180-e92a-11e9-81a4-a2601f3276a8.png)

Seems [that the way to register for the notification hub](https://forums.xamarin.com/discussion/170901/xamarin-ios-cannot-register-with-azure-notification-hub-in-ios-13-1-2) has changed so the Azure Mobile App server code needs to be updated in order to get this working again.

**Comment by asierpn** [comment]
Is anyone reading this? I know that you are not developing new features to this project, but, can we expect that current features will continue working? 

Push notifications are not working in our iOS 13 clients and we need this to be fixed.

**Comment by Jamminroot** [comment]
Hey, @asierpn, sorry for such a delay in response.
There's a work item filed, and our PMs team will look at its.

**Comment by asierpn** [comment]
Any update on this issue?

**Comment by clpolet** [comment]
Hi @asierpn, how do you collect the device token on iOS 13? I am asking because there was a subtle change in iOS 13 which broke a few people. You might be in this bucket if you are retrieving the push token through the `description` of the token data, more info here: https://nshipster.com/apns-device-tokens/.

**Comment by asierpn** [comment]
Hey @clpolet, I see, I get it from RegisteredForRemoteNotifications method in AppDelegate (Xamarin) and I pass it directly to MobileService:

    public override async void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
    {
      _deviceToken = deviceToken;
      await _mobileService.Client.GetPush().RegisterAsync(_deviceToken);
    }

**Comment by MatkovIvan** [comment]
The release of client SDK (4.1.2) with the fix for it is available now.

**Comment by asierpn** [comment]
We are still using 3.1.0, we cannot upgrade to 4.1.2 because we use server flow authentication for google and microsoft accounts and the experience with 4.x.x is horrible. We have fixed this exception creating our custom registration api and processing the device token to send the correct string to the api. If you don't apply this fixes to 3.x.x or improve server flow authentication in 4.x.x,  this fixes are useless to us.
