### ISSUE TITLE
.NET Core branch

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-apps-net-server#35]
Just wondering if there was any existing branch for migration of the server sdk for asp.net 5 and .net core? 

If so, I'd love to contribute to the process, but didn't want to repeat any work if it was being done elsewhere.

**Comment by adrianhall** [comment]
Hi @damienpontifex - we are kicking off an unofficial branch within VSTS - would be happy to have you assist and contribute.  Let me know if you wish an invite.

**Comment by damienpontifex** [comment]
Hi @adrianhall that would be great. My email from here would be best (damien.pontifex@gmail.com) for an invite.

Looking forward to it.

**Comment by prajaybasu** [comment]
Now that they've been RTM'd, is there any ETA for the .NET Core (netcoreapp1.0) compatible version of these packages ?

**Comment by adrianhall** [comment]
@prajaybasu The .NET Core framework has been RTM'd.  Unfortunately, there is additional pieces we need - most notably EF7 and OData libraries.   Until both of these stabilize and RTM, we are at a standstill on this.

**Comment by prajaybasu** [comment]
@adrianhall Fair enough; BTW, Do you plan on moving to project.json ?

**Comment by paulbatum** [comment]
@prajaybasu project.json is being replaced, for more info see https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

**Comment by prajaybasu** [comment]
@adrianhall What about projects that do not use SQL databases ?

**Comment by adrianhall** [comment]
@prajaybasu We have not done any serious thought into what will go into the .NET Core edition, since we can't actually do any work on it, as previously described.  Anything I say here would be very premature.

Let me turn that around - what sort of data sources are you interested in and why?

**Comment by thor089** [comment]
Hi

Is there any Update?
EF Core was released on June 27th as far as I know.
Odata Core was RTM on August 22nd? 
https://www.nuget.org/packages/Microsoft.OData.Core/7.0.0
Thanks

**Comment by adrianhall** [comment]
It has made it onto our backlog.  Follow issue #97 for the .NET Core upgrade.    Note, however, that we are prioritizing Visual Studio Mobile Center and client updates at this time, so this won't make it to the top of the priority list for quite some time.

**Comment by gayan1991** [comment]
Hi, is there any samples for table control in .net core? I am really struggling to upgrade azure mobile service app to asp.net core api app...!

**Comment by codegrue** [comment]
It's been a year since the last contributor post here. Any progress to report?
