### ISSUE TITLE
NH Registration Tag Support

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps-net-server#36]
We need to restore the ability to have the client able to send tags along to the server (and be approved)  

In v1, we allowed a code hook to allow developer to customize / reject  generate tags.

Possibly a white/blacklist could work for the simple case if its easier as a workaround. 

Original issue found in: https://github.com/Azure/azure-mobile-services/issues/762#issuecomment-160671013

**Comment by phvannor** [comment]
Node.js copy: https://github.com/Azure/azure-mobile-apps-node/issues/241

**Comment by adrianhall** [comment]
Superceded by Azure/azure-mobile-services-pr#342
