### ISSUE TITLE
Make CORS work when running locally (i.e. developer mode)

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-net-server#38]
Azure App Service handles CORS explicitly through the Settings -> CORS options.  When running within Azure App Service, the SDK should not do any CORS handling, delegating that functionality to the App Service.

If the server is running locally in development mode, CORS should "do the right thing" - likely allowing localhost:*.  This will allow the user to develop locally without the server getting in the way.

**Comment by adrianhall** [comment]
Ref azure-mobile-apps-node#245

**Comment by CendaL** [comment]
It took me a while to figure out I am missing CORS handlig. I have add this:
`config.EnableCors(new EnableCorsAttribute("*", "*", "*"));`
`app.UseAppServiceAuthentication(new AppServiceAuthenticationOptions()`
`...`

**Comment by adrianhall** [comment]
Documented in WIKI
