### ISSUE TITLE
pushClient.SendAsync should be obsolete

### ISSUE THREAD

**Issue by ysxu** [Azure/azure-mobile-apps-net-server#39]
This belongs to v1 where zumo wrapped nh's send apis. We are directing customers to communicate with nh directly to perform sends in v2 so should mark this method obsolete. I've already chatted with @paulbatum and @aziel about it -- there is one test (sendAsync) that is using this api, and we agreed that this change is not considered a breaking change.

**Comment by aziel** [comment]
Fixed in this merge:
https://github.com/Azure/azure-mobile-apps-net-server/pull/45
