### ISSUE TITLE
Missing WEBSITE_AUTH_SIGNING_KEY

### ISSUE THREAD

**Issue by afladmark** [Azure/azure-mobile-apps-net-server#41]
Hiya,

I'm attempting to implement custom login using the sample code provided for the preview. It all seems to come together except that I don't have a WEBSITE_AUTH_SIGNING_KEY environment variable in my Azure mobile app to send to the AppServiceLoginHandler.CreateToken method as my secretKey.

I've configured Authentication, I've checked in Kudu and I have a dozen other WEBSITE_AUTH_* environment variables. On a Mobile app that's a few weeks old I do have the old MS_SigningKey variable (which I tried for shiggles and it didn't work either), but if I create a new Mobile app it doesn't have either of those keys.

Have I missed something? Is there another way to get this key? Is there a bug?

Your assistance is greatly appreciated.

Andrew

**Comment by brettsam** [comment]
If you don't have that var, then it may be a bug. Just to double-check, you have:

1. Turned on App Service Authentication (and I'm guessing not configured any Providers?) following the steps here: https://azure.microsoft.com/en-us/blog/announcing-app-service-authentication-authorization/
2. Visited https://{yoursite}.scm.azurewebsites.net/env and search the page for 'SIGNING' and you don't find anything? Does WEBSITE_AUTH_ENABLED = true? 
3. Tried restarting your site and refreshing the kudu page? This shouldn't be necessary but couldn't hurt.
4. Tried turning App Service Authentication off, save, then back on, save.

If all of that doesn't work to get you a WEBSITE_AUTH_SIGNING_KEY and WEBSITE_AUTH_ENABLED = true, you can always set a WEBSITE_AUTH_SIGNING_KEY *App Setting* with a custom signing key* and App Service Auth should use that instead. Although you may be in an odd state if things are enabled and you have no signing key. But give all of that a try and let me know what you find.

\* Note: The signing key can't be any string, it needs to be a SHA-256 hashed string. I've been using http://www.xorbin.com/tools/sha256-hash-calculator to generate signing keys for testing purposes.

**Comment by afladmark** [comment]
Thank you for your reply.

1. Yes, it was your article I used to set it up in the first place. I initially just turned it on and saved. I didn't get the key so I setup Facebook.

2. Yes. I have checked that. Here's the related tags that are present (with some values redactions as xxx):

"WEBSITE_AUTH_TOKEN_STORE":"True","WEBSITE_AUTH_ALLOWED_AUDIENCES":"http://xxx.azurewebsites.net","ScmType":"None","WEBSITE_AUTH_EXTERNAL_REDIRECT_URLS":"http://xxx.azurewebsites.net","WEBSITE_AUTH_ENABLED":"True","WEBSITE_AUTH_FB_SCOPE":"email","WEBSITE_AUTH_MSA_SCOPE":"","WEBSITE_AUTH_UNAUTHENTICATED_ACTION":"AllowAnonymous","WEBSITE_AUTH_FB_APP_SECRET":"xxx","WEBSITE_AUTH_FB_APP_ID":"xxx","WEBSITE_AUTH_AUTO_AAD":"False","MS_SigningKey":"xxx","WEBSITE_AUTH_DEFAULT_PROVIDER":"AzureActiveDirectory"

3. and 4. Yup. Twice. With a restart or two in there for good measure. Nada I'm afraid. I've done this on an existing site and a new one I created just in case it was something legacy related. The only difference is the lack of the MS_SigningKey on the newer instance.

5. OK. I've done this. I added the value as an App Setting for WEBSITE_AUTH_SIGNING_KEY. It then appears in Kudu. I've used my login method to get a new token and passed that token to a method restricted with [Authorize] and it works just fine whereas previously it failed. So.. all good code wise, just no idea why I don't get a WEBSITE_AUTH_SIGNING_KEY by default.

Thank you for your help! I'm happy to give you any more information you need or test things if you want to look into it further.

**Comment by brettsam** [comment]
I'm not sure either -- I'll leave this issue open and see if I can get someone that knows more about signing key provisioning to weigh in. They may want some more info from you. Thanks for bringing this up.

**Comment by adrianhall** [comment]
@afladmark Are you still having issues here?

**Comment by afladmark** [comment]
Apologies for the delay in replying. I have just retested this by launching a new Mobile App and configuring it for Authentication/Authorization per @brettsam's previous instructions. It appears to have worked correctly and a WEBSITE_AUTH_SIGNING_KEY is present on the /env page as expected. I've not tested it from code, but this was obviously missing previously. I'd say consider this resolved from my perspective. Happy to check anything further if it would be helpful.

**Comment by adrianhall** [comment]
Great to hear.

**Comment by nhwilly** [comment]
Just happened to me, following the instructions in [this wonderful guide by @adrianhall ](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/debugging/)

Everything seems to be working without it.  Not sure how to put it in there...

**Comment by FrancoisM** [comment]
My custom authentication works whereas I never had a WEBSITE_AUTH_SIGNING_KEY.
Is this normal?

**Comment by winnicki** [comment]
I'm having the same issue with WEBSITE_AUTH_ALLOWED_AUDIENCES missing from my SCM environment variables. This is from the published .NET mobile app backend Azure Todo sample.

**Comment by adrianhall** [comment]
Apparently, WEBSITE_AUTH_ALLOWED_AUDIENCES is not available unless you configure AAD (after a discussion with the engineer).  The Audience should be https://{WEBSITE_HOSTNAME}/ - replace {WEBSITE_HOSTNAME} with the hostname of your site.

**Comment by winnicki** [comment]
Alright thanks. I was already using that setting.

**Comment by adrianhall** [comment]
I've filed an issue on myself in the book to update the docs in the book to match reality.
