### ISSUE TITLE
Need way to determine the provider that was used to create an auth token

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-net-server#43]
Server 0.3.36.0.

GetAppServiceIdentityAsync is defined here: https://github.com/Azure/azure-mobile-apps-net-server/blob/0.3.36.0/src/Microsoft.Azure.Mobile.Server.Authentication/Extensions/IPrincipalExtensions.cs

In a TableController method I can call the following with only one authentication type and get the data for both if the email address matches between the two services (I have only tested Facebook and Google, but this may be applicable to others as well):

```
//In a TableController trying to get the unique provider user because of the issues mentioned here with the ProviderCredentials.UserId: https://github.com/Azure/azure-mobile-apps-net-server/issues/33

var facebookIdentity = await user.GetAppServiceIdentityAsync<FacebookCredentials>(request);
var googleIdentity = await user.GetAppServiceIdentityAsync<GoogleCredentials>(request);

var  facebookUniqueProviderUserId = facebookIdentity.FindFirstValue(ClaimTypes.NameIdentifier);

var  googleUniqueProviderUserId = googleIdentity.FindFirstValue(ClaimTypes.NameIdentifier);

  public static string FindFirstValue(this ProviderCredentials principal, string claimType)
        {
            if (principal == null)
            {
                throw new ArgumentNullException(nameof(principal));
            }
            var claim = principal.Claims.FirstOrDefault(c => c.Key == claimType);
            return !(string.IsNullOrWhiteSpace(claim.Value)) ? claim.Value : null;
        }
```

Because there is no way to determine the provider type in the Azure Mobile App Service that I am aware of, we normally resort to trying both for the GoogleCredentials and FacebookCredentials, returning which one returns a value. In this new case, they both return and therefore I need to find another way to determine the provider service to hit until this can be fixed.

Thanks,

John

**Comment by renzska** [comment]
I've verified that the zumo auth token changes between the accounts being logged in on the service side using the following:
```
 string zumoAuthToken = request.GetHeaderOrDefault("x-zumo-auth");
            services.GetTraceWriter().Error("zumoauth: " + zumoAuthToken);
```

**Comment by brettsam** [comment]
Let me reiterate your scenario to make sure I understand your goal:

1. You want to pull the provider's unique identifer for a user to look it up in your own db.
2. If a user logs in with Google first, then later logs in with Facebook (and they use the same email for both), you want to treat that person as two different users in the context of your app. 

At the moment, there's no way to tell which provider was used to create a token. We're discussing a way to enable that and I can loop back when we have a solution.

Another quick note: Your auth tokens from different providers will be different but the 'sid' inside them is the same. You can plug any token into http://jwt.io to see its payload, which is a debugging method we use a lot.

**Comment by renzska** [comment]
@brettsam You are correct on both counts. If they login with different providers, I want each account to be unique. However, if there was a way to guarantee a unique id shared between the providers based off a value that does not change, that would be the preferred method, but given that the email address is really the only key identifying information, and that it can be changed, that presents a problem.

A possible solution (given that I've seen the "sid:nameidentifier" change without warning) on my side is to store the email address and unique provider id per provider in the same user account. For example:

Id - Email - FacebookUserId - GoogleUserId

I then use the "Id" field which is unique to the combination, and make sure that all users with the same provider email join in on that Id. I would then need a way to double-check that if the email changes, I can refer back to the Provider Specific UserId and notify the user in some way to allow for user consolidation.

However (and there seem to be a lot of these) there are cases where they want to have different accounts for the different providers, but in the majority of cases, I could see issues where people don't remember which provider they used and would prefer to have it so they could get to their information regardless of the provider they logged into.

Are there any best practices by Microsoft or others in this area?

----

To the issue reported though, the token for the Facebook account and for the Google account both have the same payload information except for the differing times on exp. I'm assuming this is why I can access both the Facebook and Google information for an account with just the one account having logged in, because they share the same sid on the payload.

Thanks for the tip on jwt.io. That definitely helps debugging.

**Comment by brettsam** [comment]
We definitely need to provide a mechanism for seeing which provider logged in and I'll leave this issue open until that is ready for consumption.

But as a workaround until that is ready, I think you should be able to pass a query string key/value pair like 'provider=facebook' along with your requests. The client would need to track that state but I think it would work until we get a real solution in place. It's not ideal, but it may unblock you for now.

If you can get that to work, it should let you keep every provider id as unique user in your backend. Then you'd know which to pick if you have multiple providers matched on the sid.

As for best practices -- I don't think anything is written up, but it looks like you're on the right track. You'd create a user with it's own unique id that had providerid columns for each provider. If the email/'sid' matched you could match them up automatically when a user logged in with their second provider. Merging existing accounts and handling cases without matching emails would be tougher and probably require some custom UI, but should be do-able in a similar fashion. You may actually need to track multiple emails per user -- since they may have different ones for each provider.

**Comment by brettsam** [comment]
_As of right now, there is a fix for this that is currently rolling out to all Azure websites. I wanted to give a heads-up as I'll be out for the holidays, but it's possible that your site(s) have not yet received the update._

App Service Authentication will now include an 'idp' claim in the token that is issued. This means that you can determine the login provider without tracking any extra state on the client or server.

You can access the provider from within a controller method by looking at the "http://schemas.microsoft.com/identity/claims/identityprovider" claim. The value of that Claim will be "facebook", "google", "aad", etc.

```
ClaimsPrincipal principal = this.User as ClaimsPrincipal;            
string provider = principal.FindFirst("http://schemas.microsoft.com/identity/claims/identityprovider").Value;
```

**Comment by renzska** [comment]
@brettsam I just tested it against my Azure site and it worked! Thanks for this.
