### ISSUE TITLE
Unable to get local UseAppServiceAuthentication debugging to work. More details needed

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-net-server#44]
This may be a developer issue, but I haven't been able to get the UseAppServiceAuthentication example working to debug my service locally with Authorization as mentioned here: https://github.com/Azure/azure-content/blob/master/articles/app-service-mobile/app-service-mobile-dotnet-backend-how-to-use-server-sdk.md#local-debugging-with-authentication

With the following settings, in my local service ouput I see calls going to "http://localhost/.auth/login/google" or "facebook" when calling LoginAsync with my client using the MobileServiceClient(localhost) constructor.

No matter what I set the ValidAudience and ValidIssuer to (remote azure host or local host), it always tries to call the authentication endpoints locally as mentioned above which shows a 404 on the popup login screen.

Here is the output:

> iisexpress.exe Information: 0 : Request, Method=GET, Url=http://localhost/.auth/login/google, Message='http://10.211.55.3:58208/.auth/login/google'
iisexpress.exe Information: 0 : Message='Will use same 'XmlMediaTypeFormatter' formatter', Operation=XmlMediaTypeFormatter.GetPerRequestFormatterInstance
iisexpress.exe Information: 0 : Message='Selected formatter='XmlMediaTypeFormatter', content-type='application/xml; charset=utf-8'', Operation=DefaultContentNegotiator.Negotiate
iisexpress.exe Information: 0 : Response, Status=404 (NotFound), Method=GET, Url=http://localhost/.auth/login/google, Message='Content-type='application/xml; charset=utf-8', content-length=unknown'

I have pulled the SigningKey as mentioned in the article.

Thanks,

John

```
 if (string.IsNullOrEmpty(settings.HostName))
            {
                // This middleware is intended to be used locally for debugging. By default, HostName will
                // only have a value when running in an App Service application.
                app.UseAppServiceAuthentication(new AppServiceAuthenticationOptions
                {
                    SigningKey = ConfigurationManager.AppSettings["SigningKey"],
                    ValidAudiences = new[] { ConfigurationManager.AppSettings["ValidAudience"] },
                    ValidIssuers = new[] { ConfigurationManager.AppSettings["ValidIssuer"] },
                    TokenHandler = config.GetAppServiceTokenHandler()
                });
            }
```

**Comment by renzska** [comment]
I updated to the latest GA version 1.0.119.0 and updated the above code to use the config.GetAppServiceTokenHandler() and I'm still experiencing the same issue.

**Comment by brettsam** [comment]
The login needs to call your actual service ({yoursite}.azurewebsites.net/.auth/facebook) in order to get a real token. That token can then be used locally and it will be validated by the AppServiceAuth middleware for testing your logic.

Which Mobile App client are you using? If .NET you should be able to set `AlternateLoginHost` on your `MobileServiceClient` to have logins go to your real service while all other calls continue to hit localhost. https://github.com/Azure/azure-mobile-apps-net-client/blob/master/sdk/src/Microsoft.WindowsAzure.MobileServices/MobileServiceClient.cs#L78

**Comment by renzska** [comment]
@brettsam Setting the MobileServiceClient.AlternateLoginHost to {yoursite}.azurewebsites.net did the trick. I wasn't sure what that was referring to in the article. Thanks!

**Comment by renzska** [comment]
I made a blog post about it that brings everything together in one place. If you have any suggestions, please let me know.

http://www.systemsabuse.com/2015/12/04/local-debugging-with-user-authentication-of-an-azure-mobile-app-service/

**Comment by brettsam** [comment]
Nice! Thanks for writing that all up, John.
