### ISSUE TITLE
Current version throws a Bad Request error when properties in the mobile app data model are passed to it that do not exist in the service data model

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-net-server#46]
The 0.2x version of mobile apps net server allowed you to pass an object to say, an insertasync method, that had properties that did not exist in the server model and the insert would work fine. Now, in the last two versions, 0.3 and 1.0 GA, when I pass an object that has extra properties that exist in the app data model but not the service data model, I get a bad request response from the server without any specifics to what is causing the issue directly (you have to dig deep into the response httpmessages to find the properties that show "an error occurred". If I go through and add [JsonIgnore] to the properties on the client data model, it works correctly. I can understand it's better to not include extra data to pass to the service that is going to be ignored anyway, but is there a better way to determine what fields are causing the issue (better errors). Can we have it still work even if extra properties are passed, but log a warning instead?

**Comment by phvannor** [comment]
This is due to the inclusion of https://github.com/Azure/azure-mobile-apps-net-server/blob/8c5b6b52b12b8d9f04a0be8b2fabfb749d7c0919/src/Microsoft.Azure.Mobile.Server/Config/MobileAppControllerAttribute.cs#L69

**Comment by renzska** [comment]
I tried setting that to false and still had the same result: `serializerSettings.CheckAdditionalContent = false;`.

**Comment by brettsam** [comment]
Where did you try setting it? Right now the MobileAppControllers create a new set of SerializerSettings so anything you set up outside of the controller won't be applied. For example, if you check `this.Configuration.Formatters.JsonFormatter.SerializerSettings.CheckAdditionalContent` from within a controller, it will likely still be true.

There are (less-than-ideal) ways to customize this for all controllers. I'm actually looking at improving this right now and added an issue to track it: https://github.com/Azure/azure-mobile-apps-net-server/issues/48

I can write up the steps to do this for all controllers, but first can you try doing something like this in one of your controllers and see if it gets things working the way you want?

```
protected override void Initialize(HttpControllerContext controllerContext)
{
    base.Initialize(controllerContext);
    this.Configuration.Formatters.JsonFormatter.SerializerSettings.CheckAdditionalContent = false;
}

**Comment by renzska** [comment]
I set it inside the `public static void ConfigureMobileApp(IAppBuilder app)` method originally, which did not work. I just tested it in one of my controllers and that still did not work.

I removed the [JsonIgnore] from a property "Points" and added the line you mentioned in the Initialize method of the controller. The same exception occurred. The images linked below show the detailed exception information showing the value of the CheckAdditionalContent as false.

https://www.dropbox.com/s/q4wm1zublicyqp7/Screenshot%202015-12-08%2013.39.34.png?dl=0
https://www.dropbox.com/s/7yhwuouo6j68c7h/Screenshot%202015-12-08%2013.41.05.png?dl=0

**Comment by brettsam** [comment]
Actually I think the setting you may want to change is `this.Configuration.Formatters.JsonFormatter.SerializerSettings.MissingMemberHandling = MissingMemberHandling.Ignore;`

**Comment by renzska** [comment]
That looks like the more appropriate call. I'll give it a test and let you know my results.

**Comment by brettsam** [comment]
I've added a nicer fix for this. It's not yet released on nuget but you can clone and build the solution if you want to try it out. I wrote up some background here: https://github.com/Azure/azure-mobile-apps-net-server/wiki/Configuring-MobileAppController-and-TableController-Settings
