### ISSUE TITLE
Debug mode for .Net server

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-mobile-apps-net-server#47]
Investigate debug mode for .Net server. Return full stack trace in response

**Comment by brettsam** [comment]
@pragnagopa: Do you have a specific scenario that you want to make sure works here? Using ExceptionFilters is the likely way to do it but I want to document a before/after to make sure I've fixed your issue. I assume this is mostly for the E2E tests?

**Comment by brettsam** [comment]
Oh, I think this may be b/c the E2E tests simply return "An error has occured" when deployed to a real site. The fix is to add `config.IncludeErrorDetailPolicy = IncludeErrorDetailPolicy.Always`. Without this, Web API will only return full error details when running locally. PR coming in a sec.

**Comment by adrianhall** [comment]
Is this fixed now?

**Comment by adrianhall** [comment]
Assuming fixed, based on the merged PR.
