### ISSUE TITLE
Implement custom authentication with new auth feature

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-net-server#5]

**Comment by brettsam** [comment]
I'm not sure if we want to mark this completely as 'done' yet but the new Login assembly and nuget package contains a method for creating tokens that can be authenticated by App Service Authentication. There's a small snippet in our announcement blog post here: https://azure.microsoft.com/en-us/blog/azure-mobile-apps-november-2015-update/ (see the *.NET Server SDK release candidate* section).
