### ISSUE TITLE
.NET Endpoints should return header with runtime versions (for client check on V1 client running against V2 server)

### ISSUE THREAD

**Issue by aziel** [Azure/azure-mobile-apps-net-server#56]

**Comment by phvannor** [comment]
Not sure I follow, a v1 client can't talk to a v2 server.  Any call it makes will result in a 400, missing required header response.

**Comment by aziel** [comment]
I was copying cards from backlog, this card may have been resolved with the
ZUMO-API-VERSION from client

**Comment by brettsam** [comment]
Yeah, I don't think we're going to do this now that we have ZUMO-API-VERSION. That should protect us from v1 clients accidentally accessing v2 servers.
