### ISSUE TITLE
Enable local development of user authentication feature

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-net-server#6]

**Comment by PaulAchess** [comment]
It's actually already feasable using OWIN, OAuthAuthorizationServerOptions and JWT Tokens.

I have this running on my solution, the new update make it even simpler to do (I no longer need to hack my way to owin).

I have the project to make a huge post on my blog on « how to do it » but I haven't taken the time yet. 

If you want help with this, I'll gladly provide some, even if you only want to see how I did it.

But if you want my opinion, I think a custom authentication server, next to the application server, is the best way to go. I realized that providing account management & claims is completely independant from all the business logic. 
If I had time, I would refactor this to create another webapp, dedicated for authentication (accounts + tokens), and enable cross-server authentication.

If you want to include it to Azure as a service, it could be a simple « auth web-app » to deploy on the same App Services Plan. I think it should be decoupled, it would be waaaay easier for the end-users.

**Comment by mattchenderson** [comment]
We have a solution in the works which should be getting pushed to the repo shortly, but if you do get a blog post out, we'd love to see it. Also appreciate any comments when we get the current code out, and on the proposal here:
The general idea is that we do have a hosted authentication server which a local client would talk to, and the locally-running server would have an optional middleware which could be configured to validate tokens issued by the hosted server. Thoughts there?

**Comment by PaulAchess** [comment]
This seems a pretty good start, I'll gladly look up at the code once it's pushed!

But this would only work for a single webapp? I think the solution could be way larger, as a part of Azure App Services. 

Currently we configure third-party authentication providers on the gateway and this authentication is shared between apps (API, web, mobile, …).
I think the same mechanism for custom auth would be a big plus for Azure App Services, and it is quite feasable, as all apps use the same token interpretation mechanism.

I'll be honest with you, open sourcing AMS helped me a lot to updgrade to your latest version. To build my first solution, I had to decompile the library to understand how to generate tokens correctly.

**Comment by mattchenderson** [comment]
Glad to hear the OSS is helping! Custom auth should be coming as part of the same push, actually. The functionality is per-site, but we have been talking a bit about one site to rely on another for auth, like you said (and similar to the gateway concept). Nothing concrete there right now, though.

**Comment by mattchenderson** [comment]
We got the PR in yesterday (https://github.com/Azure/azure-mobile-apps-net-server/pull/19) which adds local dev. Can now validate tokens minted by a hosted site while still on local box.
