### ISSUE TITLE
Passing in Extended LifeTime Facebook Token to LoginAsync Still Sets Azure Authentication Token to 1 Hour

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-net-server#60]
As mentioned here, the lifetime for tokens in Azure Mobile App Services has been changed: 
https://github.com/Azure/azure-mobile-apps-net-server/issues/42

I have just implemented the Facebook SDK and am getting tokens that are valid for 60 days:

![screenshot 2015-12-14 11 07 50](https://cloud.githubusercontent.com/assets/13021263/11789327/f6a76020-a252-11e5-90b7-b4fd31461176.png)

However, when I pass that token into the LoginAsync method for Azure, I still have an Azure token of 1 hour, verified by passing the `user.MobileServiceAuthenticationToken` to jwt.io and seeing the expiration value at timestamp.pro.

`var jToken = JObject.FromObject(new {access_token = token});
						user = await AzureService.Instance.Client.LoginAsync(provider, jToken);`

Is this a bug or am I missing something in the process?

Thanks,

John

**Comment by brettsam** [comment]
Unfortunately this is part of the same bug, which is part of App Service Authentication. I'll leave this issue open until it is fixed and deployed.

**Comment by renzska** [comment]
@brettsam In the meantime, I was able to use the AuthHandler I mentioned in the reference issue, https://github.com/Azure/azure-mobile-apps-net-server/issues/42, to just re-auth the user to the service using a JObject of the Facebook 60 day token, which doesn't display any sort of "re-login interface". This does the job for now without affecting the user experience.

**Comment by Jtango18** [comment]
Hi all,

Many updates on when we can expect an update to land that resolves this?

**Comment by cgillum** [comment]
This issue has been resolved in the App Service platform layer.  When logging in using your Facebook access token, you should get a long-lived JWT expiration.

**Comment by renzska** [comment]
Thanks for this!
