### ISSUE TITLE
Prescriptive Entity Structures - Private Classes and Methods

### ISSUE THREAD

**Issue by benjaminjnr** [Azure/azure-mobile-apps-net-server#69]
I particularly like the way the AspNet.Identity apis are structured using generics.  This allows people to use all kinds of data types as ids for their objects.  This is not so with the Azure Mobile SDK that forces string as the id (where the default value is a GUID) and clustering around CreatedAt field.

I agree that generics can add a certain layer of complexity, so the onus can be put on each team to do all the necessary remapping and implement its own SQLGenerator.

We have succeeded in doing this but have hit a roadblock.  We cannot inherit from the existing EntityDomainManager`1 easily because a number of methods are private. The alternative is to reimplement the entire class in our specific project.

We really need to get at the Lookup(string id, bool includeDeleted) method to cast/convert the id from string to what is used in our database and prevent the EF query from failing.

In the Microsoft.Azure.Mobile.Server assembly:
Can they be made protected internal at least?  ie Lookup, UpdateAsync, VerifyUpdatedKey.

Also can the following classes be made public: CommonResources, EFResources, and EntityUtils?

**Comment by adrianhall** [comment]
This feature will not be added.  

If you need a new DomainManager, implement IDomainManager - the EntityDomainManager has resitrictions that make the service work.

**Comment by benjaminjnr** [comment]
Do you care to provide a little more detail as to why?
