### ISSUE TITLE
Bring back the "Try it out" help page from Mobile Services

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-net-server#7]

**Comment by damienpontifex** [comment]
Considering the choice of API Apps to use Swagger/Swashbuckle for this type of feature, wouldn't it be better to follow that lead rather than having a custom 'try it out'?

**Comment by brettsam** [comment]
Agree on the Swagger approach. I've started looking into it.

**Comment by damienpontifex** [comment]
As per API apps, my thoughts would be it would be great to include it in the template for a new mobile apps project and a documentation page on adding it to an existing project. 

But not adding it as a dependency to the mobile apps SDK.

**Comment by brettsam** [comment]
New Swagger nuget has been checked in; docs coming to the wiki soon.

**Comment by brettsam** [comment]
Added some docs: https://github.com/Azure/azure-mobile-apps-net-server/wiki/Adding-Swagger-Metadata-and-Help-UI-to-a-Mobile-App
