### ISSUE TITLE
IPrincipal.GetAppServiceIdentityAsync drops claims with same names.

### ISSUE THREAD

**Issue by vodesoft** [Azure/azure-mobile-apps-net-server#70]
I tuned an Azure AD application to return groups during user impersonation using "groupMembershipClaims": "All". If an user is a member of several groups claims contain several items with name groups:
...
aud: 8b48...
iss: https://sts.windows.net/51b8...
...
groups: 96e4...
groups: c0e1...
groups: abcd...
...

But if I tried to get provider claims by calling IPrincipal.GetAppServiceIdentityAsync on the Mobile App side I got a one row per claim name:

var mobileAppUser = principal as ClaimsPrincipal;
var credentials = await mobileAppUser.GetAppServiceIdentityAsync\<AzureActiveDirectoryCredentials\>(requestMessage);
var someGroupOnlyHere = credentials.Claims["groups"];

As I see this is a deep internal limitation in Microsoft.Azure.Mobile.Server.Authentication/Extensions/IPrincipalExtensions.cs:

internal static void PopulateProviderCredentials(TokenEntry tokenEntry, ProviderCredentials credentials)
        {
            if (tokenEntry.UserClaims != null)
            {
                credentials.Claims = new Dictionary<string, string>();
                foreach (ClaimSlim claim in tokenEntry.UserClaims)
                {
                    credentials.Claims[claim.Type] = claim.Value;
                }
            }

Is there any method how to get full list of claims with claim name duplicates as it is in the TokenEntry.UserClaims? Do you plan to extend SDK or provide some kind of workaround? Thanks.

**Comment by sguryev** [comment]
Have the same issue

**Comment by brettsam** [comment]
Thanks for bringing this to our attention. I'm working on a fix now that would use a NameValueCollection instead of a Dictionary so there can be duplicate keys.

As for a workaround, there is a way that you can get access to the response and modify it before it is turned into a `ProviderCredentials` object. That gives you access to the identity info coming back from App Service Authentication.

Here's one way to do that -- this will take all duplicate claims types and combine them into one, with each value separated by semicolons. So `credentials.Claims["groups"]` would equal something like `96e4...;c0e1...;abcd...`. It'd then be up to you to split that into an array. 

Create a new MessageHandler:
```
public class DuplicateClaimMessageHanlder : DelegatingHandler
{
    public DuplicateClaimMessageHanlder(HttpMessageHandler innerHandler) :
        base(innerHandler)
    {
    }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        HttpResponseMessage response = await base.SendAsync(request, cancellationToken);
        JObject result = await response.Content.ReadAsAsync<JObject>();
        if (result.HasValues && result["user_claims"] != null)
        {
            JArray claims = result.GetValue("user_claims") as JArray;

            // match all claims by their 'typ', only returning ones with more than one member in the group
            var matchingTypes = claims.GroupBy(c => c["typ"].ToString().ToLowerInvariant()).Where(g => g.Count() > 1);

            foreach (IGrouping<string, JToken> matchGroup in matchingTypes)
            {
                // get all values for that group
                string[] values = matchGroup.Select(c => c["val"].ToString()).ToArray();

                // remove all of the matches
                foreach (JToken match in matchGroup)
                {
                    claims.Remove(match);
                }

                // put everything into a new object with the values concatenated in 'val'
                JObject newGroup = new JObject();
                newGroup["typ"] = matchGroup.Key;
                newGroup["val"] = string.Join(";", values);

                claims.Add(newGroup);
            }

            response.Content = new StringContent(result.ToString(), Encoding.UTF8, "application/json");
        }
        return response;
    }
}
```

Then pass that when calling `GetAppServiceIdentityAsync`:
```
HttpClient httpClient = new HttpClient(new DuplicateClaimMessageHanlder(new HttpClientHandler()));
var user = await this.User.GetAppServiceIdentityAsync<AzureActiveDirectoryCredentials>(this.Request, httpClient);
```
