### ISSUE TITLE
Getting System.OutOfMemoryException while consuming Mobile Apps with varbinary datatype

### ISSUE THREAD

**Issue by apoorvg** [Azure/azure-mobile-apps-net-server#81]
Requirement: I have a table with one of the fields as VarBinary(MAX) and storing big documents in it. I need to download the data for this table on to my Mobile Client. 

Implementation: I created a Mobile Apps project and exposed the table via an Entity (sample below - only relavant portions) and the controller. 
 public class ClassName
    {
        public byte[] Data { get; set; }
    }

```
public class ClassNameController : TableController
{
    public virtual IQueryable<T> GetAllRecords()
    {
           return Query();
     } 
}
```

The table has 50 records. 

When I try to consume this Mobile Apps controller (via my mobile client or fiddler) for get all records, I get an exception as System.OutOfMemoryException during serialization. 

Is there any limitation on using binary datatype? 
Is there any other recommended approach to sync these records?

Exception Details:
{"message":"An error has occurred.","exceptionMessage":"Exception of type 'System.OutOfMemoryException' was thrown.","exceptionType":"System.OutOfMemoryException","stackTrace":" at System.IO.MemoryStream.set_Capacity(Int32 value)\r\n at System.IO.MemoryStream.EnsureCapacity(Int32 value)\r\n at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)\r\n at System.Net.Http.HttpContent.LimitMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)\r\n at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)\r\n at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)\r\n at Newtonsoft.Json.Utilities.Base64Encoder.WriteChars(Char[] chars, Int32 index, Int32 count)\r\n at Newtonsoft.Json.Utilities.Base64Encoder.Encode(Byte[] buffer, Int32 index, Int32 count)\r\n at Newtonsoft.Json.JsonTextWriter.WriteValue(Byte[] value)\r\n at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializePrimitive(JsonWriter writer, Object value, JsonPrimitiveContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal(JsonWriter jsonWriter, Object value, Type rootType)\r\n at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)\r\n at System.Web.Http.OData.Query.Expressions.SelectExpandWrapperConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)\r\n at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)\r\n at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n at System.Web.Http.Owin.HttpMessageHandlerAdapter.d__13.MoveNext()"}

**Comment by fabiocav** [comment]
Managing large documents with this approach will be challenging, principally when you start bringing this data down to the mobile device where resources are even more constrained.
You may want to look at this blog post https://azure.microsoft.com/en-us/blog/file-management-with-azure-mobile-apps/
It covers a new file sync feature that uses recommended patterns to manage files/blobs, storing them in Azure Storage.

**Comment by apoorvg** [comment]
I had looked at File Sync briefly before raising this query. Based on the brief look, the File Sync did not fit my requirement as this was tied to Blob Storage. I will try this out in more depth over new couple of days. 

As per my current requirements, the documents are stored within DB. As for client application, it will run on laptops, hence there are no constraints on Processing power or storage power. 

To overcome the Out of memory exception, I tried few things as below:
1. tried to reduce the batch size during Pull operation to say 3 records so that memory constraint is not there. Ran into issues with big files like 25 MBs. So this solution is ruled out. 
2. Tried to provide my own customized serialization format to try and compress the file. Tried with adding JsonConvert attribute on the byte[] property, but the custom converter was not picked up. Anything I might be missing here?

Other Solutions - need to try:
1. I will be creating a custom controller (not inheriting from TableController) and use streaming logic to render the file to the client. Use "InvokeApi" method on the client SDK to call this. Do you see any limitations / things that I might be missing since I will not use TableController?

File Sync:
As mentioned above, based on the brief look, the File Sync did not fit my requirement as this was tied to Blob Storage. 
1. Is my assumption above correct?
2. If yes, does it allow to use (via customization / extensibility) any other storage mechanism apart from Blob Storage?

**Comment by adrianhall** [comment]
Hi @apoorvg 

What storage mechanism would fit your requirements?  25Mb is large for a data blob, so there must be other details here.

**Comment by adrianhall** [comment]
No update in 9 months - closing for lack of interest.
