### ISSUE TITLE
Add overload for GetIdentitiesAsync that only requires the X-ZUMO-AUTH token value

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-mobile-apps-net-server#87]
Specifically for SignalR; this is referenced in Issue #82.

**Comment by PaulARoy** [comment]
I can make a PR for this if you want

**Comment by tofutim** [comment]
@PaulARoy did this ever get integrated? I am using SignalR.

**Comment by adrianhall** [comment]
Nothing happened to us!  This never got a PR submitted, so we never integrated.

**Comment by PaulARoy** [comment]
Sorry, I did not find the time to do this PR at that time and completely forgot. I currently use the workaround referenced on https://github.com/Azure/azure-mobile-apps-net-server/issues/82 if you need it.

**Comment by adrianhall** [comment]
Thanks @PaulARoy and @tofutim - I'm working on getting this PR merged in on our side.  I don't see any problems with it - just need another engineer to review, pass the end to end tests, probably add another test to check the full functionality.... it's a process.

**Comment by tofutim** [comment]
Dear Adrian,

Thanks!

Would there be an interest in putting this repo into CI? Then the tests
would be automatically run for all PRs.

Cheers,
Tim

**Comment by adrianhall** [comment]
Unfortunately, the end to end tests can't be run automatically...   We run them with both a server and a client, and we have .NET (Xamarin/iOS, Xamarin/Android, Xamarin/Forms, UWP, Win8, Win8.1, WinPhone8, WInPhone8.1), iOS Native, Android Native, JavaScript and Apache Cordova (iOS, Android, UWP) to run - that's 14 different end to end tests with different environments to run.    We wouldn't be able to do that without a complete rearchitecture of the end to end tests.

**Comment by pvbchak** [comment]
Fixed in https://github.com/Azure/azure-mobile-apps-net-server/pull/190
