### ISSUE TITLE
Local Debug, GetAppServiceIdentityAsync throws 'System.ArgumentOutOfRangeException' if signing key is wrong

### ISSUE THREAD

**Issue by aziel** [Azure/azure-mobile-apps-net-server#90]
May extend to more scenarios than Local Debug...
But if the token can't be decoded for whatever reason (signing key is wrong, or token minted with diff key is sent), the this.User.Claims has zero length.
We get a OOR exception because we're looking for the "iss" key in GetAppServiceIdentityAsync.

We should swallow this exception in GetAppServiceIdentityAsync and provide a more generic exception message.

**Comment by aziel** [comment]
@mattchenderson How do you want to solve this?  Is the custom exception message ok?

**Comment by lindydonna** [comment]
@mattchenderson Any update?

**Comment by brettsam** [comment]
The ArgumentOutOfRangeException should have a message explaining that 'iss' is missing from the Claims and therefore we can't proceed (https://github.com/Azure/azure-mobile-apps-net-server/blob/master/src/Microsoft.Azure.Mobile.Server.Authentication/Extensions/IPrincipalExtensions.cs#L63). I think this is accurate -- I want to make sure we're explicit about why things failed so it's easier to debug.

In this scenario where the token isn't validated, I'm assuming that IsAuthenticated = false. App developers should really be checking that before calling GetAppServiceIdentityAsync. We *could* check that first internally and throw an explicit exception that you need to be authenticated to call this API. We need to think whether there's any scenario that this would break (but I can't think of any off the top of my head).
