### ISSUE TITLE
Refresh Token process not implemented - Causes re-auth issues with Google (maybe Facebook)

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-net-server#93]
Using the Google Sign iOS SDK I am able to get the id_token, access_token, authorization_code, and refresh_token. The problem is that when authenticating to Azure, I get an hour session and the service does nothing with the refresh_token to get new valid tokens. This causes my app to have to show the login screen every time the token expires (1 hour).

In the case of Facebook, I can resend my access token and it lets me continue using Azure (related bug with Azure Facebook here: https://github.com/Azure/azure-mobile-apps-net-server/issues/60).

I've read on the forums here: https://social.msdn.microsoft.com/Forums/azure/en-US/1765c45d-c70e-44bd-ad6f-0b2659ec634f/authentication-tokens-expiring-quickly?forum=azuremobile, that they are working on working on the refresh token process. I wanted to create an issue here to officially track it. The Uservoice request for it is here: https://feedback.azure.com/forums/216254-mobile-apps-formerly-mobile-services/suggestions/11182890-implementation-of-refresh-tokens-for-azure-app-ser

If you need any additional information, please let me know.

**Comment by brettsam** [comment]
Thanks. I'll leave this issue open until the solution is rolled out. We'll have more information and docs available as soon as it is ready for consumption.

**Comment by brettsam** [comment]
@cgillum has written a [great blog post](http://cgillum.tech/2016/03/07/app-service-token-store/) documenting the token store. It explains how to use the new App Service Authentication feature for refreshing tokens (see the **Refreshing Tokens** section). There is a specific code sample there for Mobile Apps.
