### ISSUE TITLE
automapper update issues

### ISSUE THREAD

**Issue by gaambo** [Azure/azure-mobile-apps-net-server#96]
hi there, 
automapper has updatet its API - and the static way of working with automapper will soon be obsolete - so it would be awesome if the mobile apps server sdk also would go the new way of using automapper in the mappedentitydomainmanager. 

also i'm having problems with the mappedentitydomainmanager since this week. in the mappedentitydomainmanager `Project().To<TData>()` is used in the query and lookup function to project the model to the dto objects. it seems this method is from an older version of automapper and i'm getting the following missingmethodexception
`System.MissingMethodException: Method not found: "AutoMapper.QueryableExtensions.IProjectionExpression AutoMapper.QueryableExtensions.Extensions.Project(System.Linq.IQueryable`1<!!0>)".`

my workaround is to manually get the data from the db context and use the working `.ProjectTo<>(expandingAttributes)` method. but i would appreciate it, if you could fix it in the mappedentitydomainmanager

**Comment by gaambo** [comment]
my workaround is to override the query/lookup methods in my simplemappedentitydomainmanager with the following
`IQueryable<TDTOModel> query = this.Context.Set<TModel>().ProjectTo<TDTOModel>();
            query = TableUtils.ApplyDeletedFilter(query, this.IncludeDeleted);
            return query;`

this still uses the static way of automapper and will be obsolete with version 5.0

**Comment by brettsam** [comment]
Thanks for reporting this. What version of AutoMapper are you using where you see `MissingMethodException` above?

**Comment by gaambo** [comment]
i'm using automapper nuget version 4.2.0 and mobile.server & mobile.server.tables 1.1.157.1

**Comment by deman4ik** [comment]
Same with automapper 4.2.1.0 and mobile.server 1.1.157.1

**Comment by damienpontifex** [comment]
I have found the issue when having a go at integrating AutoMapper v4.2 that "Argument type 'IMapper' is not CLS-compliant". This comes from having the `IMapper` interface in the `MappedEntityDomainManager` constructor for DI as I believe is the recommended way moving forward.

Making it CLS-compliant is also tracked on the AutoMapper repo at AutoMapper/AutoMapper#1072

**Comment by aline-almeida** [comment]
I'm also having this issue. Any news on this ?

**Comment by brettsam** [comment]
I've created a PR (#131) to move the solution forward to AutoMapper 4.2.1. The unit tests all pass so I'm fairly confident this will work but please let me know if you think I'm missing a scenario.

I did a little investigating this morning. Here's what I've found:

- Re: static -- [static APIs are back as of 4.2.1](https://lostechies.com/jimmybogard/2016/02/24/automapper-4-2-1-released-static-is-back-limited-edition/). I believe we could move to using IMappers inside the MappedEntityDomainManager by requiring you to register your IMapper with the DI engine. But unless there's a great reason to do so, I think sticking with the static methods keeps things easier. Any objections? 

- Re: MissingMethodException -- changing `Project().To<TData>()` to `ProjectTo<TData>()` got things compiling and all tests passing. I *think* that's the only remaining issue.

 @damienpontifex -- if you use the static initialization, then the fact that IMapper isn't CLS-compliant (until 5.0) shouldn't matter, right?

**Comment by migig** [comment]
The bug is still there. Any indication when this will be fixed?

(We don't use a IOC tool, so I hope the fix won't force us to change our system.)

**Comment by brettsam** [comment]
We've not done an official release with the fix, but I've set up a feed on myget.org with a daily build that has the latest changes. I haven't documented it anywhere (yet) but please give it a try. The SLA for this feed will be something like "Use at your own risk. These packages have passed all unit tests but may not have had any testing past that." If you find any issues there, please let us know. The feed info:

- Nuget v3: https://www.myget.org/F/azure-mobile/api/v3/index.json
- Nuget v2: https://www.myget.org/F/azure-mobile/api/v2

**Comment by migig** [comment]
Seems good, but unfortunately our company's policy doesn't allow me to use betas in production. :cry:

I've noticed that the other SDKs are regularly updated (e.g. NotificationHubs, which is updated often), but this one not so often. Are you allowed to share what is the typical release cadence for the client and server SDKs? Once per year, once in a while, etc.?

**Comment by adrianhall** [comment]
For the update of all the libraries, #164 is tracking the work.  We'll do a release as soon as all the E2E tests pass.  We don't have a specific cadence - it's basically when we do work on it.  Since we are a small team and have a number of products and SDKs, it doesn't get updated as often as you expect.

Closing as a dup of #164.
