### ISSUE TITLE
Support ASP.NET Core / EF7 / .NET Core Semantics

### ISSUE THREAD

**Issue by jiberan** [Azure/azure-mobile-apps-net-server#97]
EntityDomainManager is expecting DbContext from EF6. There should be also version for Entity Framework Core.

**Comment by adrianhall** [comment]
Hi @jiberan - we do not support ASP.NET Core at this time.  Feel free to file a UserVoice at http://feedback.azure.com - I'm sure others are waiting on it as well.

**Comment by Nimrodxx** [comment]
He @adrianhall do you have any plans for supporting ASP.NET Core? Since it has already been released for a month. I'm figuring out if I should be my mobile backend with ASP.net core or with the regular ASP.net framework. OfflineSync is a must have for me...

**Comment by adrianhall** [comment]
You should use the regular ASP.NET framework for right now.

**Comment by jraadt** [comment]
It's been a few months and I see there's a .net core milestone now.  Has this moved from backlog to active development?  Just curious if there's an update.

**Comment by adrianhall** [comment]
We are still waiting for a couple of features within EF7 and a release of the OData provider before we can begin work.  We've done some light investigation, but waiting for these libraries is holding us back.

**Comment by adrianhall** [comment]
Check out my blog on https://shellmonger.com - I'm starting a series where I discuss running things in .NET Core, which will include EF7 and Azure Mobile Apps.  This project will NOT be going to .NET Core - the differences are significant enough that we will be starting a new project to support .NET Core going forward.  Look for this in the future - it isn't going to be quick.

**Comment by Ponant** [comment]
Hi @adrianhall , I asked this question (compatibility between Azure Mobile Apps and .Net Core) and after your response we worked on the ASP.NET Core web app, hoping that the Azure Mobile App will get updated in the meanwhile to support .Net Core. Could you give us a rough indication of the timeline such that we know how to proceed? Are we talking about 3 months, 6 months, a year or more? Approximately.

**Comment by adrianhall** [comment]
I am no longer with Microsoft, so I can't answer this.   Personally, I'd look for an alternate solution to this.

**Comment by chadiswar** [comment]
Adrian was this move based on a product shift in the Azure app service or was this a personal decision?

**Comment by Ponant** [comment]
Hi @adrianhall , I am sorry to hear this as I know your contributions to Azure. Which alternate solution would you have in mind? It is not clear to us what altenatives we have, identity server? We need to keep our .Net Core app but be able to communicate with Azure from a mobile app (UWP and then Xamarin). cheers

**Comment by adrianhall** [comment]
AUthentication and configuration are already taken care of (I've done the work for handling the [Authorize] token and it is released on NuGet - check out my blog at https://shellmonger.com and my NuGet libraries).  After that, just create a regular REST API and use that.

**Comment by Ponant** [comment]
If that is what you mean, http://www.nuget.org/packages/AzureAppService/, it would be great to point to an explicit post in your blog where you use this library. The closes I go t was this one, https://shellmonger.com/2017/03/02/azure-app-service-authentication-in-an-asp-net-core-application/, but it does not seem to use your lib.

**Comment by adrianhall** [comment]
Yep - that is the one.  The code is the same - I just encapsulated the library code in an actual library.
