### ISSUE TITLE
CreatedAt, UpdatedAt, Version are always Null

### ISSUE THREAD

**Issue by ChrisTowles** [Azure/azure-mobile-apps-net-server#98]
I'm trying to use this framework for sync as well as cache however the models returned by `TableController `always have null for `CreatedAt`, `UpdatedAt`, and `Version `properties. Thus for as i understand it making sync impossible. I'm using a `EntityDomainManager` and Nuget Version 1.1.157.1.

I believe my model has the correct properties so would expect them to populate correctly.

        #region System properties
        public string Id { get; set; }
        public byte[] Version { get; set; }   
        public DateTimeOffset? CreatedAt { get; set; }
        public DateTimeOffset? UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        #endregion

Digging deeper I tried to use a `MappedEntityDomainManager `instead however it actual had trouble writing the objects headers for the response due to the Version Tag.resulting in this error. 

        message: "An error has occurred.",
        exceptionMessage: "The value cannot be null or empty. Parameter name: tag",
        exceptionType: "System.ArgumentException",
        stackTrace: " at System.Net.Http.Headers.EntityTagHeaderValue..ctor(String tag, Boolean isWeak) at Microsoft.Azure.Mobile.Server.Tables.TableQueryFilter.GetETagFromVersion(Byte[] version) at Microsoft.Azure.Mobile.Server.Tables.TableQueryFilter.AddETagResponseHeader(HttpResponseMessage response)

i can make it not error by setting the version byte array field to anything, just for testing. 

        //TODO: Hack, don't do this, test only 
        result.First().Version = new byte[] { 0x1 };

Am i doing something wrong or am i misunderstanding something basic. What experience are others having?

**Comment by ChrisTowles** [comment]
I think I've solved my problems with the Azure Mobile SDK Syncing. My problem was two fold.

First I failed to understand that the UpdatedAt, CreatedAt and Version will all be null on the client untill the objected inserted on the server. The server database will generate these properties and return them to the client with the sync.

Second make sure all the correct Attributes are populated on the Server Model. This is really important as if you are using EF Code First this affects SQL Triggers and Constrains that populate the CreatedAt, UpdatedAt Columns. As well the Version Column is a timestamp type.

In my case my code first was not generating the trigger and EF didn't see the columns as Computed so it was inserting null into these fields.

[Azure Sync Client Model ](https://gist.github.com/ChrisTowles/a44208643f9e09fb39c8)
[Azure Sync Server Model ](https://gist.github.com/ChrisTowles/e10c843706e5a3f6f778)

Currently i'm working on a DB First solution and I'll try to follow up with more infomation to help others not doing code first EF.

**Comment by adrianhall** [comment]
Thanks Chris.  I'm glad it's sorted. 

Feel free to ping me offline with your observations.   We can always put a wiki article together around this topic.

**Comment by isamllr** [comment]
Having the same issue - tried to remove the fields completely (in my server & client solution) as documented. Since that did not work, I tried to use @ChrisTowles solution - no luck, I always get complaints about trying to insert NULL as CreatedAt. Any ideas?

**Comment by isamllr** [comment]
Was able to solve it, did not follow this template for my DB since creating from existing tables.

CREATE TABLE [dbo].[ConstructionSite](	
	[Site_Heads] [bigint] NULL,
	[Id]NVARCHAR (128) DEFAULT (newid()) NOT NULL,
	[Version] [timestamp] NOT NULL,
	[CreatedAt] DATETIMEOFFSET (7) DEFAULT (sysutcdatetime()) NOT NULL,
	[UpdatedAt] [datetimeoffset](7) NULL,
	[Deleted] [bit] NOT NULL,
 CONSTRAINT [PK_dbo.ConstructionSite] PRIMARY KEY NONCLUSTERED ([Id] ASC)
);

CREATE CLUSTERED INDEX [IX_CreatedAt]
    ON [dbo].[ConstructionSiteDBs]([CreatedAt] ASC);

GO

I did not find this in the documentation (might be my fault). The documentation should mention somewhere what the schema is supposed to look like if not created automatically.

**Comment by winnicki** [comment]
When I was debugging locally my code first was able to create the database. After publishing for some reason it keeps timing out even though I increased both the connection and command timeouts. 

I went to just script the table over but initially forgot to grab the trigger which generates these values so that was my mistake.

**Comment by mintyfusion** [comment]
Good documentation for this feature: https://adrianhall.gitlab.io/develop-mobile-apps-with-csharp-and-azure/chapter3/server/

In addition, there has to be Trigger for UpdatedAt as well

`CREATE TRIGGER [TR_dbo_Examples_InsertUpdateDelete] ON [dbo].[Examples]
    AFTER INSERT, UPDATE, DELETE AS
    BEGIN
        UPDATE [dbo].[Examples]
            SET [dbo].[Examples].[UpdatedAt] = CONVERT(DATETIMEOFFSET, SYSUTCDATETIME())
            FROM INSERTED WHERE inserted.[Id] = [dbo].[Examples].[Id]
    END;`

**Comment by sisaacks** [comment]
@ChrisTowles do you have an example of what you did....I am facing the same issue as you.  I am using code first.  I am absolutely confused on what my models should look like on the client vs the server involving attributes.  I saw that some of yours are TableData???
